# FUSION AVEC CODE

**Objectif** : Ajouter les codes associés à certaines modalités de variables 

Pour les varibales  ci dessous se trouvant  dans la base de travail qui sont des chaînes de caractère , on souhaite ajouter les codes associés à leur différentes modalités.
Pour ce faire, il faut utiliser un autre fichier excel où se trouve ces modalités et leurs codes pour chacune des variables.

Les variables en question sont : 


* Fonction
* Services
* Organismes
* Echelons
* Emplois
* Lieu d'affectation

# Il faut céer un fichier excel avec plusieurs feuille , contenant les mapings finaux  sauf lieu d'affectation

## Chargement des packages necessaires

In [47]:
# Paramètres
import io
import pandas as pd
import boto3
import pandas as pd
import io
import pandas as pd
import unicodedata
import re

import pandas as pd
import numpy as np
import unicodedata
import re

import pandas as pd
import unicodedata, re

## Chargement de la base de travail

In [48]:
# Connexion S3
s3_client = boto3.client(
 "s3",
 endpoint_url="http://minio.mon-namespace.svc.cluster.local:80", # service interne K8s
 aws_access_key_id="wer1Or8j7hXa3QGk2M3M",
 aws_secret_access_key="YtbyBd3Y0bEYeDy8aeX3lAf4JIUlKYlxY8lNVTVt",
 verify=False # à désactiver si SSL auto-signé ; sinon mettre True avec certificat valide
)

# Paramètres
bucket_name = "admindataanstat"
object_key = "Solde/panel_solde_df_280725.parquet"

# Télécharger l'objet depuis S3
obj = s3_client.get_object(Bucket=bucket_name, Key=object_key)

# Charger dans un DataFrame depuis le fichier Parquet
panel_solde_df = pd.read_parquet(io.BytesIO(obj['Body'].read()))

# Afficher un aperçu
panel_solde_df.head()

,MATRICULE||CODE_ORGANISME,MATRICULE,NOM,DATE NAISSANCE,SEXE,SITUATION MATRIMONIALE,NOMBRE ENFANT,LIEU AFFECTATION,SERVICE,ORGANISME,...,DATE_NAISSANCE_CORRIGEE,ANNEE_NAISSANCE_CORRIGEE,MOIS_NAISSANCE_CORRIGEE,JOUR_NAISSANCE_CORRIGEE,AGE,AGE_VALIDE,SEXE_VALIDE,AGE_IMPUTE,SITUATION_MATRIMONIALE_RECODE,NBRE_ENFTS_IMPUTE
0,011242X15,011242X,DOSSO MEGBO,1939-01-01,Masculin,Marié,0.0,Seguela,D. G. A. A. T.,Min. d'Etat Administration du Territoire,...,1939-01-01,1939.0,1.0,1.0,76.0,NaN,Masculin,41.0,Marié(e),0.0
1,012856Q15,012856Q,KHISSY BEYNIOUAH FULBERT,1939-01-01,Masculin,Célibataire,0.0,Bouaké,D. G. A. A. T.,Min. d'Etat Administration du Territoire,...,1939-01-01,1939.0,1.0,1.0,76.0,NaN,Masculin,41.0,Célibataire,0.0
2,013454N15,013454N,VAHA TOMAS GNOMBLEI HENRI,1924-01-01,Masculin,Marié,0.0,Guiglo,D. G. A. A. T.,Min. d'Etat Administration du Territoire,...,1924-01-01,1924.0,1.0,1.0,91.0,NaN,Masculin,41.0,Marié(e),0.0
3,027861L25,027861L,CAPET YATO MATHIEU,1943-03-01,Masculin,Marié,0.0,Abidjan,A affecter,"Min. Affaires Etrangères, de l'Intégration Afr...",...,1943-03-01,1943.0,3.0,1.0,71.0,NaN,Masculin,41.0,Marié(e),0.0
4,039659M38,039659M,COULIBALY YOUSSOUF,1945-12-01,Masculin,Marié,2.0,Abidjan,Dir Personnel Police Nationale,Min. de l'Intérieur et de la Sécurité,...,1945-12-01,1945.0,12.0,1.0,69.0,69.0,Masculin,69.0,Marié(e),2.0

## Chargement du fichier pour la jointure avec le fichier de travail (panel_solde_df) contenant les codes de : 

* Fonction
* Lieu d'affectation
* Services
* Organismes
* Echelons
* Emploi

In [49]:
# Paramètres S3
bucket_name = "admindataanstat"
object_key = "Solde/FICHIER_ANSTAT_CODE_2025.xlsx"  

# Télécharger le fichier depuis S3 dans un buffer mémoire
obj = s3_client.get_object(Bucket=bucket_name, Key=object_key)
bytes_io = io.BytesIO(obj['Body'].read())

# Remettre le curseur au début
bytes_io.seek(0)

0

* Affichage des différentes feuilles du fichiers excel

In [51]:
xlsx = pd.ExcelFile(bytes_io)
print("Feuilles disponibles :", xlsx.sheet_names)

Feuilles disponibles : ['lieu affectation', 'ORGANISME_OK', 'CODE_SITUATION_SOLDE', 'HISTORIQUE_ECHELLES_CORPS', 'ECHELLES_CORPS_ACTUEL', 'service', 'FONCTION', 'grade']

# CREATION DES FONCTIONS NECESSAIRES

## Utilitaires généraux (normalisation, écriture Excel)

In [52]:
import pandas as pd
import numpy as np
import re
import unicodedata
from pathlib import Path

def normalize_label(s: str) -> str:
    """Minuscules, accents retirés, ponctuation uniformisée, espaces compressés."""
    if pd.isna(s):
        return ""
    s = str(s).strip()
    s = (s.replace("-", " ")
           .replace("’", "'")
           .replace("'", " ")
           .replace(".", " "))
    s = s.lower()
    s = unicodedata.normalize("NFKD", s)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = re.sub(r"\s+", " ", s).strip()
    return s

def _pick_excel_engine():
    try:
        import openpyxl  # noqa
        return "openpyxl"
    except Exception:
        try:
            import xlsxwriter  # noqa
            return "xlsxwriter"
        except Exception:
            raise RuntimeError("Installez 'openpyxl' ou 'xlsxwriter' pour écrire dans Excel.")

def _pick_excel_engine():
    try:
        import openpyxl  # noqa
        return "openpyxl"
    except Exception:
        try:
            import xlsxwriter  # noqa
            return "xlsxwriter"
        except Exception:
            raise RuntimeError("Installez 'openpyxl' ou 'xlsxwriter' pour écrire dans Excel.")

def write_sheet(df: pd.DataFrame, workbook_path: str, sheet_name: str):
    """
    Écrit/Remplace la feuille `sheet_name` dans `workbook_path`.
    - Si le classeur n'existe pas: création sans if_sheet_exists.
    - S'il existe: append + replace de la feuille.
    """
    engine = _pick_excel_engine()
    xlsx = Path(workbook_path)

    if engine == "openpyxl":
        if xlsx.exists():
            # append + replace la feuille
            with pd.ExcelWriter(workbook_path, engine="openpyxl", mode="a", if_sheet_exists="replace") as xw:
                df.to_excel(xw, sheet_name=sheet_name, index=False)
        else:
            # création (pas de if_sheet_exists en mode 'w')
            with pd.ExcelWriter(workbook_path, engine="openpyxl", mode="w") as xw:
                df.to_excel(xw, sheet_name=sheet_name, index=False)
    else:
        # xlsxwriter: on doit recharger les feuilles existantes pour les réécrire
        sheets = {}
        if xlsx.exists():
            try:
                with pd.ExcelFile(workbook_path) as xf:
                    for sn in xf.sheet_names:
                        sheets[sn] = xf.parse(sn)
            except Exception:
                sheets = {}
        sheets[sheet_name] = df
        with pd.ExcelWriter(workbook_path, engine="xlsxwriter") as xw:
            for sn, d in sheets.items():
                d.to_excel(xw, sheet_name=sn, index=False)

    print(f"✅ Feuille écrite : {sheet_name} → {workbook_path}")

## Chargement + Paramètres + Vérifs de base

In [53]:
def read_reference(
    excel_source,
    sheet_name: str,
    required_cols=None,          # ex: ["CODE_FONCTION","LIBELLÉ_FONCTION"]
    alias_map: dict | None = None, # alias optionnel {col_source: col_cible}, appliqué UNIQUEMENT ici
    drop_title_substr: str | None = "TABLEAU",  # supprime les lignes dont la 1ʳᵉ colonne contient ce motif
    preview_rows: int = 5,
) -> pd.DataFrame:
    """
    Lit une feuille Excel, affiche un aperçu AVANT/APRÈS nettoyage et retourne le DataFrame propre.

    Nettoyage :
      - supprime lignes entièrement vides
      - supprime lignes “titre” si la 1ʳᵉ colonne contient `drop_title_substr` (ex: 'TABLEAU')
      - si besoin, promeut la 1ʳᵉ ligne en entête
      - applique un alias de colonnes (optionnel, UNIQUEMENT au chargement)
      - vérifie la présence des colonnes `required_cols` si fourni
    """

    # --- Lecture brute ---
    df_raw = pd.read_excel(excel_source, sheet_name=sheet_name)

    print(f"\n=== {sheet_name} | APERÇU BRUT (top {preview_rows}) ===")
    try:
        from IPython.display import display
        display(df_raw.head(preview_rows))
    except Exception:
        print(df_raw.head(preview_rows).to_string(index=False))
    print(f"Colonnes BRUTES ({sheet_name}) :", df_raw.columns.tolist())
    print(f"Shape brut : {df_raw.shape}")

    # --- Copie de travail ---
    df = df_raw.copy()

    # 1) Supprimer les lignes entièrement vides
    df = df.dropna(how="all")

    # 2) Supprimer les lignes de titre si la 1ʳᵉ colonne les contient (ex: 'TABLEAU')
    if drop_title_substr is not None and not df.empty:
        first_col = df.columns[0]
        mask_title = df[first_col].astype(str).str.contains(drop_title_substr, case=False, na=False)
        df = df.loc[~mask_title].copy()

    # 3) Re-détecter l'entête si nécessaire (heuristique simple)
    def _looks_like_header(row_vals, required, alias):
        vals = [str(v).strip() for v in row_vals]
        if required and any(c in vals for c in required):
            return True
        if alias and any(src in vals for src in alias.keys()):
            return True
        if any("unnamed" in v.lower() for v in vals):
            return False
        if any(("code" in v.lower()) or ("lib" in v.lower()) for v in vals):
            return True
        return False

    if not df.empty:
        candidate = df.iloc[0].tolist()
        if _looks_like_header(candidate, required_cols, alias_map):
            df.columns = [str(v).strip() for v in candidate]
            df = df.drop(df.index[0]).reset_index(drop=True)

    # 4) Alias de colonnes (optionnel, seulement au chargement)
    if alias_map:
        df = df.rename(columns=alias_map)

    # 5) Vérifier les colonnes requises (si fourni)
    if required_cols:
        missing = [c for c in required_cols if c not in df.columns]
        if missing:
            print("\n⚠️ Colonnes manquantes après nettoyage/alias :", missing)
            print("Colonnes disponibles :", df.columns.tolist())
            raise ValueError(f"Colonnes manquantes : {missing}")

    # 6) Aperçu après nettoyage
    print(f"\n=== {sheet_name} | APRÈS NETTOYAGE (top {preview_rows}) ===")
    try:
        from IPython.display import display
        display(df.head(preview_rows))
    except Exception:
        print(df.head(preview_rows).to_string(index=False))
    print(f"Colonnes NETTOYÉES ({sheet_name}) :", df.columns.tolist())
    print(f"Shape nettoyé : {df.shape}")

    return df.reset_index(drop=True)





def check_code_to_label_uniqueness(df_ref: pd.DataFrame, var_code_ext: str, var_lib_ext: str) -> pd.Series:
    """
    Vérifie que chaque code (var_code_ext) pointe vers un seul libellé (var_lib_ext).
    Retourne la série des codes non-uniques (counts).
    """
    verif_code = df_ref.groupby(var_code_ext)[var_lib_ext].nunique()
    bad = verif_code[verif_code > 1]
    if bad.empty:
        print("✅ Chaque code est associé à un seul libellé.")
    else:
        print("❌ Codes associés à plusieurs libellés :")
        print(bad)
    return bad

def ensure_normalized_column(df_ref: pd.DataFrame, var_lib_ext: str, var_norm_ext: str | None = None) -> str:
    """
    Ajoute la colonne normalisée (var_norm_ext) si absente. Retourne son nom.
    """
    var_norm_ext = var_norm_ext or f"{var_lib_ext}_NORM"
    if var_norm_ext not in df_ref.columns:
        df_ref[var_norm_ext] = df_ref[var_lib_ext].apply(normalize_label)
    return var_norm_ext

def detect_normalized_duplicates(df_ref: pd.DataFrame, var_norm_ext: str) -> pd.Series:
    """
    Détecte les libellés normalisés répétés (plusieurs lignes partagent la même clé normalisée).
    """
    lib_counts = df_ref[var_norm_ext].value_counts()
    lib_repetes = lib_counts[lib_counts > 1]
    if lib_repetes.empty:
        print("✅ Aucun doublon détecté (normalisation).")
    else:
        print(f"❌ Doublons détectés (normalisés) : {len(lib_repetes)} libellés en double.")
    return lib_repetes

## Construction du mapping (1 code par libellé normalisé)

In [54]:
def build_random_mapping(df_ref: pd.DataFrame, var_norm_ext: str, var_code_ext: str, var_lib_ext: str,
                         seed: int = 123) -> pd.DataFrame:
    """
    Construit un mapping 1 code / clé normalisée :
      - choisit aléatoirement un code quand plusieurs existent (traçable par seed),
      - ajoute les colonnes d’audit : EST_AMBIGU, NB_CODES_POSSIBLES, CODES_POSSIBLES.
    Sortie : DataFrame avec colonnes [var_lib_ext, var_norm_ext, var_code_ext,
                                     EST_AMBIGU, NB_CODES_POSSIBLES, CODES_POSSIBLES, CODE_CHOISI]
    """
    df = df_ref.copy()
    # infos par clé
    codes_list = (df.groupby(var_norm_ext)[var_code_ext]
                    .apply(lambda s: sorted(map(str, pd.unique(s))))
                    .rename("CODES_LIST"))
    codes_info = codes_list.to_frame()
    codes_info["NB_CODES_POSSIBLES"] = codes_info["CODES_LIST"].str.len()
    codes_info["EST_AMBIGU"] = codes_info["NB_CODES_POSSIBLES"].gt(1)
    codes_info["CODES_POSSIBLES"] = codes_info["CODES_LIST"].apply(lambda L: ", ".join(L))

    # tirage aléatoire d'un code par clé normalisée
    pairs_uniques = df[[var_norm_ext, var_code_ext]].drop_duplicates()
    selection = (pairs_uniques.groupby(var_norm_ext, group_keys=False)
                 .apply(lambda g: g.sample(n=1, random_state=seed))
                 .reset_index(drop=True)
                 .rename(columns={var_code_ext: "CODE_CHOISI"}))

    # mapping final = libellé brut x clé norm + code choisi + audit d’ambiguïté
    mapping = (df[[var_lib_ext, var_norm_ext]]
               .drop_duplicates()
               .merge(selection, on=var_norm_ext, how="left")
               .merge(codes_info.drop(columns=["CODES_LIST"]), left_on=var_norm_ext, right_index=True, how="left"))
    mapping[var_code_ext] = mapping["CODE_CHOISI"]

    cols = [var_lib_ext, var_norm_ext, var_code_ext, "CODE_CHOISI", "EST_AMBIGU",
            "NB_CODES_POSSIBLES", "CODES_POSSIBLES"]
    mapping = mapping[cols].sort_values([ "EST_AMBIGU", var_norm_ext, var_lib_ext ],
                                        ascending=[False, True, True])
    return mapping

def export_mapping(mapping: pd.DataFrame, workbook_path: str, sheet_name: str):
    """
    Écrit UNIQUEMENT la feuille de mapping (pas de feuille ‘Ambigus’) ;
    la feuille contient les colonnes d’audit ‘EST_AMBIGU’, ‘CODES_POSSIBLES’, etc.
    """
    write_sheet(mapping, workbook_path, sheet_name)

## Fusion du mapping dans le panel + bilan des non appariés

In [55]:
def merge_mapping_into_panel(panel_df: pd.DataFrame,
                             mapping: pd.DataFrame,
                             var_norm_panel: str, var_norm_ext: str,
                             var_code_panel: str, var_code_ext: str,
                             var_lib_panel: str):
    """
    - crée var_norm_panel si besoin,
    - merge mapping (même clé normalisée),
    - remplit var_code_panel avec le code du mapping si NA,
    - retourne (panel_df, nb_renseignes, nb_manquants).
    """
    df = panel_df.copy()
    if var_norm_panel not in df.columns:
        df[var_norm_panel] = df[var_lib_panel].apply(normalize_label)

    out = df.merge(mapping[[var_norm_ext, var_code_ext]].drop_duplicates(),
                   left_on=var_norm_panel, right_on=var_norm_ext, how="left")

    if var_code_panel not in out.columns:
        out[var_code_panel] = pd.NA
    out[var_code_panel] = out[var_code_panel].fillna(out[var_code_ext])

    nb_rens = int(out[var_code_panel].notna().sum())
    nb_miss = int(out[var_code_panel].isna().sum())
    print(f"Codes renseignés dans {var_code_panel} : {nb_rens}")
    print(f"Codes manquants dans {var_code_panel} : {nb_miss}")
    return out, nb_rens, nb_miss

def list_unmatched_norms(panel_df: pd.DataFrame, var_code_panel: str, var_norm_panel: str) -> list[str]:
    """Liste (unique) des clés normalisées non appariées dans le panel."""
    non_app = (panel_df.loc[panel_df[var_code_panel].isna(), var_norm_panel]
                      .dropna().astype(str).str.strip())
    non_app = non_app[non_app.ne("")].unique().tolist()
    print("Non appariés (n) :", len(non_app))
    return non_app

## Similarité sur les non appariés (top 1 par clé)

In [56]:
import pandas as pd

def list_unmatched_norms(panel_df: pd.DataFrame, var_code_panel: str, var_norm_panel: str):
    """Retourne la liste unique des libellés normalisés non appariés (non vides)."""
    s = (panel_df.loc[panel_df[var_code_panel].isna(), var_norm_panel]
                  .dropna().astype(str).str.strip())
    return s[s.ne("")].unique().tolist()

def best_suggestions(panel_df: pd.DataFrame, mapping: pd.DataFrame,
                     var_norm_panel: str, var_norm_ext: str,
                     var_lib_ext: str, var_code_ext: str,
                     var_code_panel: str,
                     top_n: int = 20,
                     min_score_show: int = 0) -> pd.DataFrame:
    """
    Pour chaque libellé normalisé non apparié dans le panel, calcule le MEILLEUR candidat
    du référentiel (score de similarité). Affiche le top (avec display) et retourne
    un DataFrame suggestions_best (structuré même s'il est vide).
    Colonnes de sortie : 
      [f"{var_norm_panel}_NON_APPARIE", f"MATCH_{var_norm_ext}", "MATCH_SCORE",
       var_lib_ext, var_code_ext]
    """

    # --- Entrées : non appariés (panel) et référentiel (clés normalisées) ---
    non_apparies = list_unmatched_norms(panel_df, var_code_panel, var_norm_panel)
    ref_norms = (mapping[var_norm_ext].dropna().astype(str).str.strip())
    ref_norms = ref_norms[ref_norms.ne("")].unique().tolist()

    # --- Moteur de similarité ---
    use_rapidfuzz = False
    try:
        from rapidfuzz import process, fuzz  # type: ignore
        use_rapidfuzz = True
    except Exception:
        from difflib import SequenceMatcher

    def _best_match(q: str):
        if not q or q.strip() == "":
            return None
        if use_rapidfuzz:
            # (matched_norm, score, idx_in_list)
            return process.extractOne(q, ref_norms, scorer=fuzz.token_set_ratio)
        else:
            best_score, best_idx = -1, None
            for idx, rn in enumerate(ref_norms):
                sc = int(SequenceMatcher(None, q, rn).ratio() * 100)
                if sc > best_score:
                    best_score, best_idx = sc, idx
            return (ref_norms[best_idx], best_score, best_idx) if best_idx is not None else None

    # --- Calcul des meilleurs candidats ---
    rows = []
    for qn in non_apparies:
        res = _best_match(qn)
        if res is None:
            continue
        matched_norm, score, _ = res

        # Récupérer proprement le (libellé, code) correspondant dans le mapping
        # (si plusieurs lignes : on prend la première pour stabiliser)
        cand = mapping.loc[mapping[var_norm_ext] == matched_norm, [var_lib_ext, var_code_ext]].head(1)
        if cand.empty:
            # sécurité : si le matched_norm n'est pas (ou plus) dans 'mapping'
            continue
        lib_val = cand.iloc[0][var_lib_ext]
        code_val = cand.iloc[0][var_code_ext]

        rows.append({
            f"{var_norm_panel}_NON_APPARIE": qn,
            f"MATCH_{var_norm_ext}": matched_norm,
            "MATCH_SCORE": int(score),
            var_lib_ext:  lib_val,
            var_code_ext: code_val,
        })

    # Colonnes attendues
    expected_cols = [
        f"{var_norm_panel}_NON_APPARIE",
        f"MATCH_{var_norm_ext}",
        "MATCH_SCORE",
        var_lib_ext,
        var_code_ext,
    ]

    suggestions_best = pd.DataFrame(rows)

    # --- Tri + affichage (display si possible) ---
    if suggestions_best.empty:
        # DataFrame vide mais structuré
        suggestions_best = pd.DataFrame(columns=expected_cols)
        to_show = suggestions_best
    else:
        # Trier et filtrer pour l'affichage
        suggestions_best = suggestions_best.sort_values(
            ["MATCH_SCORE", var_lib_ext], ascending=[False, True]
        )[expected_cols]
        if min_score_show > 0:
            to_show = suggestions_best[suggestions_best["MATCH_SCORE"] >= min_score_show].head(top_n)
        else:
            to_show = suggestions_best.head(top_n)

    # Affichage "Jupyter-friendly"
    try:
        from IPython.display import display
        display(to_show)
    except Exception:
        print(to_show.to_string(index=False))

    return suggestions_best

## Application des remplacements (manuel OU automatique)

In [57]:
def apply_choices(panel_df: pd.DataFrame,
                  var_code_panel: str, var_norm_panel: str,
                  choices_map: dict[str, str],
                  var_cle_panel: str, var_lib_panel: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Applique un dictionnaire {clé_norm_panel -> code}, uniquement là où le code est NA.
    Renvoie (panel_df_mis_a_jour, audit_df).
    """
    df = panel_df.copy()
    fill_mask = df[var_code_panel].isna()
    sugg_col = f"{var_code_panel}_SUGG"
    df.loc[fill_mask, sugg_col] = df.loc[fill_mask, var_norm_panel].map(choices_map)

    m_apply = df[var_code_panel].isna() & df[sugg_col].notna()
    before_col = f"{var_code_panel}_BEFORE"
    df[before_col] = df[var_code_panel]
    df.loc[m_apply, var_code_panel] = df.loc[m_apply, sugg_col]

    audit = (df.loc[m_apply, [var_cle_panel, var_lib_panel, var_norm_panel, before_col, var_code_panel]]
               .copy()
               .rename(columns={var_code_panel: f"{var_code_panel}_AFTER"}))

    print(f"✔ Lignes mises à jour : {len(audit)}")
    df.drop(columns=[sugg_col], errors="ignore", inplace=True)
    return df, audit

def auto_apply_by_score(panel_df: pd.DataFrame,
                        suggestions_best: pd.DataFrame,
                        var_code_panel: str, var_norm_panel: str,
                        var_cle_panel: str, var_lib_panel: str,
                        var_code_ext: str,
                        min_score: int = 70) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Construit choices_map pour toutes les suggestions avec score ≥ min_score, et applique.
    """
    if suggestions_best.empty:
        print("INFO : pas de suggestions à appliquer.")
        return panel_df.copy(), pd.DataFrame()

    # nom de la colonne 'clé_norm_non_apparie' dans suggestions_best
    norm_non_app_col = [c for c in suggestions_best.columns if c.endswith("_NON_APPARIE")]
    if not norm_non_app_col:
        raise ValueError("La table suggestions_best ne contient pas de colonne *_NON_APPARIE.")
    norm_non_app_col = norm_non_app_col[0]

    ok = suggestions_best[suggestions_best["MATCH_SCORE"] >= min_score]
    choices_map = dict(zip(ok[norm_non_app_col], ok[var_code_ext]))

    return apply_choices(panel_df, var_code_panel, var_norm_panel, choices_map, var_cle_panel, var_lib_panel)

In [58]:
def enrich_mapping_with_choices(mapping_final: pd.DataFrame,
                                suggestions_best: pd.DataFrame,
                                var_norm_panel: str,
                                var_norm_ext: str, var_code_ext: str, var_lib_ext: str,
                                choices_map: dict[str, str]) -> pd.DataFrame:
    """
    Ajoute dans le mapping les alias normalisés retenus (clé_norm_panel -> code),
    en remplaçant l’éventuelle ancienne ligne pour cette clé.
    """
    if suggestions_best.empty or not choices_map:
        print("INFO : rien à enrichir (pas de suggestions ou pas de choix).")
        return mapping_final

    norm_non_app_col = [c for c in suggestions_best.columns if c.endswith("_NON_APPARIE")]
    if not norm_non_app_col:
        raise ValueError("suggestions_best ne contient pas de colonne *_NON_APPARIE.")
    norm_non_app_col = norm_non_app_col[0]

    # ne garder que les suggestions dont la clé est choisie
    sel = suggestions_best[suggestions_best[norm_non_app_col].isin(list(choices_map.keys()))].copy()

    # remplacer le code par celui imposé par choices_map (au cas où)
    sel[var_code_ext] = sel[norm_non_app_col].map(choices_map)

    add = (sel[[norm_non_app_col, var_code_ext, var_lib_ext]]
             .drop_duplicates()
             .rename(columns={norm_non_app_col: var_norm_ext}))

    need_cols = {var_norm_ext, var_lib_ext, var_code_ext}
    missing = [c for c in need_cols if c not in mapping_final.columns]
    if missing:
        raise ValueError(f"mapping_final doit contenir {need_cols}, manquant : {missing}")

    before = len(mapping_final)
    # retire les anciennes lignes pour ces clés
    mapping_final = mapping_final[~mapping_final[var_norm_ext].isin(add[var_norm_ext])]
    # concatène + dédoublonne
    mapping_final = (pd.concat([mapping_final, add], ignore_index=True)
                     .drop_duplicates(subset=[var_norm_ext, var_code_ext]))
    print(f"🔁 Mapping enrichi : +{len(mapping_final)-before} lignes (net).")
    return mapping_final

## 1.Ajout des codes de FONCTION dans la base de travail

**Chargement**

* Fichier code

In [59]:
fichier_ref = "FONCTION"
df_ref = read_reference(bytes_io, fichier_ref)

=== FONCTION | APERÇU BRUT (top 5) ===

   CODE_FONCTION                                   LIBELLÉ_FONCTION
0              0
1              1  Personnel Médical Contractuel exerçant des soi...
2              2  Indemnité spécifique au Directeur de Cabinet M...
3              4  Indemnité du Chargé de Mission ou Secrétaire P...
4              5                Moniteur des Sciences Fondamentales

Colonnes BRUTES (FONCTION) : ['CODE_FONCTION', 'LIBELLÉ_FONCTION']
Shape brut : (160, 2)

=== FONCTION | APRÈS NETTOYAGE (top 5) ===

   CODE_FONCTION                                   LIBELLÉ_FONCTION
0              0
1              1  Personnel Médical Contractuel exerçant des soi...
2              2  Indemnité spécifique au Directeur de Cabinet M...
3              4  Indemnité du Chargé de Mission ou Secrétaire P...
4              5                Moniteur des Sciences Fondamentales

Colonnes NETTOYÉES (FONCTION) : ['CODE_FONCTION', 'LIBELLÉ_FONCTION']
Shape nettoyé : (160, 2)

* Base de travail

In [60]:
panel_solde_df.columns

Index(['MATRICULE||CODE_ORGANISME', 'MATRICULE', 'NOM', 'DATE NAISSANCE',
       'SEXE', 'SITUATION MATRIMONIALE', 'NOMBRE ENFANT', 'LIEU AFFECTATION',
       'SERVICE', 'ORGANISME', 'PRISE DE SERVICE', 'SITUATION',
       'DATE DEBUT SITUATION', 'EMPLOI', 'FONCTION', 'GRADE', 'CLASSE/ECHELON',
       'MONTANT BRUT', 'MONTANT NET', 'RETENUE  PENSION', 'IMPOT ',
       'CHARGE PATRONALE', 'MOIS/ANNEE', 'GRADE 2', 'AGE RETRAITE',
       'DATE RETRAITE', 'PERIODE', 'DATE_COLLECTE', 'CODE_ORGANISME',
       'ANNEE_NAISSANCE', 'MOIS_NAISSANCE', 'JOUR_NAISSANCE', 'ANNEE_COLLECTE',
       'MOIS_COLLECTE', 'JOUR_COLLECTE', 'nbre_date_naissances',
       'DATE_NAISSANCE_CORRIGEE', 'ANNEE_NAISSANCE_CORRIGEE',
       'MOIS_NAISSANCE_CORRIGEE', 'JOUR_NAISSANCE_CORRIGEE', 'AGE',
       'AGE_VALIDE', 'SEXE_VALIDE', 'AGE_IMPUTE',
       'SITUATION_MATRIMONIALE_RECODE', 'NBRE_ENFTS_IMPUTE'],
      dtype='object')

**Paramètres**

In [61]:
nm_feuille = "FONCTION" # nom de la feuille 
var_code_ext = "CODE_FONCTION"
var_lib_ext  = "LIBELLÉ_FONCTION"
var_cle_ext  = var_lib_ext

var_cle_panel  = "FONCTION"
var_code_panel = "CODE_FONCTION"
var_lib_panel  = "FONCTION"


# Noms normalisés
var_norm_ext   = f"{var_cle_ext}_NORM"
var_norm_panel = f"{var_cle_panel}_NORM"

**1) Vérification**

In [62]:
_ = check_code_to_label_uniqueness(df_ref, var_code_ext, var_lib_ext)
var_norm_ext = ensure_normalized_column(df_ref, var_lib_ext, var_norm_ext)
_ = detect_normalized_duplicates(df_ref, var_norm_ext)

✅ Chaque code est associé à un seul libellé.
❌ Doublons détectés (normalisés) : 5 libellés en double.

In [63]:
df_ref

,CODE_FONCTION,LIBELLÉ_FONCTION,LIBELLÉ_FONCTION_NORM
0,0,,
1,1,Personnel Médical Contractuel exerçant des soi...,personnel medical contractuel exercant des soi...
2,2,Indemnité spécifique au Directeur de Cabinet M...,indemnite specifique au directeur de cabinet m...
3,4,Indemnité du Chargé de Mission ou Secrétaire P...,indemnite du charge de mission ou secretaire p...
4,5,Moniteur des Sciences Fondamentales,moniteur des sciences fondamentales
...,...,...,...
155,791,Préfet région dir cab,prefet region dir cab
156,794,Régisseur d'Imprimerie National ou du Journal ...,regisseur d imprimerie national ou du journal ...
157,795,Trésorier Gr 4,tresorier gr 4
158,796,Receveur des impots,receveur des impots
159,797,Trésorier Chargé études G4,tresorier charge etudes g4

**2) Mapping aléatoire (1 code / clé) + export dans un classeur commun**

In [64]:

mapping = build_random_mapping(df_ref, var_norm_ext, var_code_ext, var_lib_ext, seed=123)
export_mapping(mapping, workbook_path="Referentiels_unifies.xlsx", sheet_name= nm_feuille)

/tmp/ipykernel_26/2242558500.py:23: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.sample(n=1, random_state=seed))

✅ Feuille écrite : FONCTION → Referentiels_unifies.xlsx

**3) Fusion dans le panel (panel_solde_df)**

In [65]:
panel_solde_df, _, _ = merge_mapping_into_panel(
    panel_solde_df, mapping,
    var_norm_panel=var_norm_panel, var_norm_ext=var_norm_ext,
    var_code_panel=var_code_panel, var_code_ext=var_code_ext,
    var_lib_panel=var_lib_panel
)

Codes renseignés dans CODE_FONCTION : 15627891
Codes manquants dans CODE_FONCTION : 72

**4) Similarité pour les non appariés (top 1 par clé)**

In [66]:
suggestions_best = best_suggestions(
    panel_solde_df, mapping,
    var_norm_panel=var_norm_panel, var_norm_ext=var_norm_ext,
    var_lib_ext=var_lib_ext, var_code_ext=var_code_ext,
    var_code_panel=var_code_panel,
    min_score_show=0
)

,FONCTION_NORM_NON_APPARIE,MATCH_LIBELLÉ_FONCTION_NORM,MATCH_SCORE,LIBELLÉ_FONCTION,CODE_FONCTION
0,tresorier charge d etudes g4,tresorier charge etudes g4,96,Trésorier Chargé études G4,797

**5a)Application MANUELLE (tu fournis tes choix)**

In [68]:

CHOIX_FORCES = {
    # "cle_norm_panel_exemple": "CODE_CHOISI"
    "tresorier charge d etudes g4": "797"
}
panel_solde_df, audit_manuel = apply_choices(
    panel_solde_df,
    var_code_panel=var_code_panel, var_norm_panel=var_norm_panel,
    choices_map=CHOIX_FORCES,
    var_cle_panel=var_cle_panel, var_lib_panel=var_lib_panel
)

/tmp/ipykernel_26/2755122773.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['797' '797' '797' '797' '797' '797' '797' '797' '797' '797' '797' '797'
 '797' '797' '797' '797' '797' '797' '797' '797' '797' '797' '797' '797'
 '797' '797' '797' '797' '797' '797' '797' '797' '797' '797' '797' '797'
 '797' '797' '797' '797' '797' '797' '797' '797' '797' '797' '797' '797'
 '797' '797' '797' '797' '797' '797' '797' '797' '797' '797' '797' '797'
 '797' '797' '797' '797' '797' '797' '797' '797' '797' '797' '797' '797']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[m_apply, var_code_panel] = df.loc[m_apply, sugg_col]

✔ Lignes mises à jour : 72

**5b) OU Application AUTO par score (≥ 70 par défaut)**

In [21]:

panel_solde_df, audit_auto = auto_apply_by_score(
    panel_solde_df, suggestions_best,
    var_code_panel=var_code_panel, var_norm_panel=var_norm_panel,
    var_cle_panel=var_cle_panel, var_lib_panel=var_lib_panel,
    var_code_ext=var_code_ext, min_score=70
)

✔ Lignes mises à jour : 72

**6a) Enrichir le mapping avec les choix retenus (manuel)**

In [70]:
#   Ici on prend les choix AUTO comme exemple :
#   on reconstruit le dict choices_map à partir d'audit_auto
if not audit_manuel.empty:
    choices_map_manuel = dict(zip(
        panel_solde_df.loc[audit_manuel.index, var_norm_panel],
        panel_solde_df.loc[audit_manuel.index, var_code_panel]
    ))
else:
    choices_map_manuel = {}

mapping = enrich_mapping_with_choices(
    mapping_final=mapping,
    suggestions_best=suggestions_best,
    var_norm_panel=var_norm_panel,
    var_norm_ext=var_norm_ext, var_code_ext=var_code_ext, var_lib_ext=var_lib_ext,
    choices_map=choices_map_manuel
)

🔁 Mapping enrichi : +-3 lignes (net).

**6b) Enrichir le mapping avec les choix retenus (auto)**

In [ ]:
#   Ici on prend les choix AUTO comme exemple :
#   on reconstruit le dict choices_map à partir d'audit_auto
if not audit_auto.empty:
    choices_map_auto = dict(zip(
        panel_solde_df.loc[audit_auto.index, var_norm_panel],
        panel_solde_df.loc[audit_auto.index, var_code_panel]
    ))
else:
    choices_map_auto = {}

mapping = enrich_mapping_with_choices(
    mapping_final=mapping,
    suggestions_best=suggestions_best,
    var_norm_panel=var_norm_panel,
    var_norm_ext=var_norm_ext, var_code_ext=var_code_ext, var_lib_ext=var_lib_ext,
    choices_map=choices_map_auto
)

In [23]:
xlsx = pd.ExcelFile(bytes_io)
print("Feuilles disponibles :", xlsx.sheet_names)

Feuilles disponibles : ['lieu affectation', 'ORGANISME_OK', 'CODE_SITUATION_SOLDE', 'HISTORIQUE_ECHELLES_CORPS', 'ECHELLES_CORPS_ACTUEL', 'service', 'FONCTION', 'grade']

## 2.Ajout des codes de SERVICES dans la base de travail

**Chargement**

* Fichier code

In [71]:
fichier_ref = "service"
df_ref = read_reference(bytes_io, fichier_ref)

=== service | APERÇU BRUT (top 5) ===

  CODE_SERVICE                  LIBELLÉ_SERVICE
0         0200                       A affecter
1         0205                Insp. Gén. d Etat
2         0210      Présidence de la République
3         02GM                  Grand Médiateur
4         02RI  Relations avec les Institutions

Colonnes BRUTES (service) : ['CODE_SERVICE', 'LIBELLÉ_SERVICE']
Shape brut : (2241, 2)

=== service | APRÈS NETTOYAGE (top 5) ===

  CODE_SERVICE                  LIBELLÉ_SERVICE
0         0200                       A affecter
1         0205                Insp. Gén. d Etat
2         0210      Présidence de la République
3         02GM                  Grand Médiateur
4         02RI  Relations avec les Institutions

Colonnes NETTOYÉES (service) : ['CODE_SERVICE', 'LIBELLÉ_SERVICE']
Shape nettoyé : (2241, 2)

* Base de travail

In [72]:
panel_solde_df.columns

Index(['MATRICULE||CODE_ORGANISME', 'MATRICULE', 'NOM', 'DATE NAISSANCE',
       'SEXE', 'SITUATION MATRIMONIALE', 'NOMBRE ENFANT', 'LIEU AFFECTATION',
       'SERVICE', 'ORGANISME', 'PRISE DE SERVICE', 'SITUATION',
       'DATE DEBUT SITUATION', 'EMPLOI', 'FONCTION', 'GRADE', 'CLASSE/ECHELON',
       'MONTANT BRUT', 'MONTANT NET', 'RETENUE  PENSION', 'IMPOT ',
       'CHARGE PATRONALE', 'MOIS/ANNEE', 'GRADE 2', 'AGE RETRAITE',
       'DATE RETRAITE', 'PERIODE', 'DATE_COLLECTE', 'CODE_ORGANISME',
       'ANNEE_NAISSANCE', 'MOIS_NAISSANCE', 'JOUR_NAISSANCE', 'ANNEE_COLLECTE',
       'MOIS_COLLECTE', 'JOUR_COLLECTE', 'nbre_date_naissances',
       'DATE_NAISSANCE_CORRIGEE', 'ANNEE_NAISSANCE_CORRIGEE',
       'MOIS_NAISSANCE_CORRIGEE', 'JOUR_NAISSANCE_CORRIGEE', 'AGE',
       'AGE_VALIDE', 'SEXE_VALIDE', 'AGE_IMPUTE',
       'SITUATION_MATRIMONIALE_RECODE', 'NBRE_ENFTS_IMPUTE', 'FONCTION_NORM',
       'LIBELLÉ_FONCTION_NORM', 'CODE_FONCTION', 'CODE_FONCTION_BEFORE'],
      dtype='object')

**Paramètres**

In [73]:
nm_feuille = "SERVICE" # nom de la feuille 
var_code_ext = "CODE_SERVICE"
var_lib_ext  = "LIBELLÉ_SERVICE"
var_cle_ext  = var_lib_ext

var_cle_panel  = "SERVICE"
var_code_panel = "CODE_SERVICE"
var_lib_panel  = "SERVICE"


# Noms normalisés
var_norm_ext   = f"{var_cle_ext}_NORM"
var_norm_panel = f"{var_cle_panel}_NORM"

**1) Vérification**

In [74]:
_ = check_code_to_label_uniqueness(df_ref, var_code_ext, var_lib_ext)
var_norm_ext = ensure_normalized_column(df_ref, var_lib_ext, var_norm_ext)
_ = detect_normalized_duplicates(df_ref, var_norm_ext)

✅ Chaque code est associé à un seul libellé.
❌ Doublons détectés (normalisés) : 180 libellés en double.

**2) Mapping aléatoire (1 code / clé) + export dans un classeur commun**

In [75]:

mapping = build_random_mapping(df_ref, var_norm_ext, var_code_ext, var_lib_ext, seed=123)
export_mapping(mapping, workbook_path="Referentiels_unifies.xlsx", sheet_name= nm_feuille)

/tmp/ipykernel_26/2242558500.py:23: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.sample(n=1, random_state=seed))

✅ Feuille écrite : SERVICE → Referentiels_unifies.xlsx

**3) Fusion dans le panel (panel_solde_df)**

In [76]:
panel_solde_df, _, _ = merge_mapping_into_panel(
    panel_solde_df, mapping,
    var_norm_panel=var_norm_panel, var_norm_ext=var_norm_ext,
    var_code_panel=var_code_panel, var_code_ext=var_code_ext,
    var_lib_panel=var_lib_panel
)

Codes renseignés dans CODE_SERVICE : 15470956
Codes manquants dans CODE_SERVICE : 157007

**4) Similarité pour les non appariés (top 1 par clé)**

In [77]:
suggestions_best = best_suggestions(
    panel_solde_df, mapping,
    var_norm_panel=var_norm_panel, var_norm_ext=var_norm_ext,
    var_lib_ext=var_lib_ext, var_code_ext=var_code_ext,
    var_code_panel=var_code_panel,
    min_score_show=0
)

,SERVICE_NORM_NON_APPARIE,MATCH_LIBELLÉ_SERVICE_NORM,MATCH_SCORE,LIBELLÉ_SERVICE,CODE_SERVICE
1,delegation de paris unesco,delegation paris unesco,93,Délégation Paris Unesco,5950
2,ppa urc,ppa_urc,85,PPA_URC,38Q5
0,e p h d,d p s d,71,D P S D,52DP

**5a)Application MANUELLE (tu fournis tes choix)**

In [78]:

CHOIX_FORCES = {
    # "cle_norm_panel_exemple": "CODE_CHOISI"
    "delegation de paris unesco": "5950","ppa urc": "38Q5"
    
}
panel_solde_df, audit_manuel = apply_choices(
    panel_solde_df,
    var_code_panel=var_code_panel, var_norm_panel=var_norm_panel,
    choices_map=CHOIX_FORCES,
    var_cle_panel=var_cle_panel, var_lib_panel=var_lib_panel
)

✔ Lignes mises à jour : 6495

**5b) OU Application AUTO par score (≥ 70 par défaut)**

In [27]:

panel_solde_df, audit_auto = auto_apply_by_score(
    panel_solde_df, suggestions_best,
    var_code_panel=var_code_panel, var_norm_panel=var_norm_panel,
    var_cle_panel=var_cle_panel, var_lib_panel=var_lib_panel,
    var_code_ext=var_code_ext, min_score=70
)

✔ Lignes mises à jour : 72

**6a) Enrichir le mapping avec les choix retenus (manuel)**

In [79]:
#   Ici on prend les choix AUTO comme exemple :
#   on reconstruit le dict choices_map à partir d'audit_auto
if not audit_manuel.empty:
    choices_map_manuel = dict(zip(
        panel_solde_df.loc[audit_manuel.index, var_norm_panel],
        panel_solde_df.loc[audit_manuel.index, var_code_panel]
    ))
else:
    choices_map_manuel = {}

mapping = enrich_mapping_with_choices(
    mapping_final=mapping,
    suggestions_best=suggestions_best,
    var_norm_panel=var_norm_panel,
    var_norm_ext=var_norm_ext, var_code_ext=var_code_ext, var_lib_ext=var_lib_ext,
    choices_map=choices_map_manuel
)

🔁 Mapping enrichi : +-58 lignes (net).

**6b) Enrichir le mapping avec les choix retenus (auto)**

In [ ]:
#   Ici on prend les choix AUTO comme exemple :
#   on reconstruit le dict choices_map à partir d'audit_auto
if not audit_auto.empty:
    choices_map_auto = dict(zip(
        panel_solde_df.loc[audit_auto.index, var_norm_panel],
        panel_solde_df.loc[audit_auto.index, var_code_panel]
    ))
else:
    choices_map_auto = {}

mapping = enrich_mapping_with_choices(
    mapping_final=mapping,
    suggestions_best=suggestions_best,
    var_norm_panel=var_norm_panel,
    var_norm_ext=var_norm_ext, var_code_ext=var_code_ext, var_lib_ext=var_lib_ext,
    choices_map=choices_map_auto
)

In [ ]:

# (Option) réécrire la feuille “FONCTION” avec le mapping enrichi
export_mapping(mapping, workbook_path="Referentiels_unifies.xlsx", sheet_name= nm_feuille)

In [33]:
xlsx = pd.ExcelFile(bytes_io)
print("Feuilles disponibles :", xlsx.sheet_names)

Feuilles disponibles : ['lieu affectation', 'ORGANISME_OK', 'CODE_SITUATION_SOLDE', 'HISTORIQUE_ECHELLES_CORPS', 'ECHELLES_CORPS_ACTUEL', 'service', 'FONCTION', 'grade']

## 3.Ajout des codes de ORGANISMES dans la base de travaiL

**Chargement**

* Fichier code

In [80]:
fichier_ref = "ORGANISME_OK"
df_ref = read_reference(bytes_io, fichier_ref)

=== ORGANISME_OK | APERÇU BRUT (top 5) ===

  CODE_ORGANISME             LIBELLÉ_ORGANISME  CODE_ÉTABLISSEMENT  CODE_ACCT
0             00      En Attente d'Affectation                   1        NaN
1             02   Présidence (Budget Général)                   1        NaN
2             03  Min Réconciliation Nationale                   1        NaN
3             04                  Cour Suprême                   1        NaN
4             05           Grande Chancellerie                   1        NaN

Colonnes BRUTES (ORGANISME_OK) : ['CODE_ORGANISME', 'LIBELLÉ_ORGANISME', 'CODE_ÉTABLISSEMENT', 'CODE_ACCT']
Shape brut : (210, 4)

=== ORGANISME_OK | APRÈS NETTOYAGE (top 5) ===

  CODE_ORGANISME             LIBELLÉ_ORGANISME  CODE_ÉTABLISSEMENT  CODE_ACCT
0             00      En Attente d'Affectation                   1        NaN
1             02   Présidence (Budget Général)                   1        NaN
2             03  Min Réconciliation Nationale                   1        NaN
3             04                  Cour Suprême                   1        NaN
4             05           Grande Chancellerie                   1        NaN

Colonnes NETTOYÉES (ORGANISME_OK) : ['CODE_ORGANISME', 'LIBELLÉ_ORGANISME', 'CODE_ÉTABLISSEMENT', 'CODE_ACCT']
Shape nettoyé : (210, 4)

In [81]:
df_ref = df_ref.rename({"CODE_ORGANISME": "ID_ORGANISME"}, axis=1)

* Base de travail

In [82]:
panel_solde_df.columns

Index(['MATRICULE||CODE_ORGANISME', 'MATRICULE', 'NOM', 'DATE NAISSANCE',
       'SEXE', 'SITUATION MATRIMONIALE', 'NOMBRE ENFANT', 'LIEU AFFECTATION',
       'SERVICE', 'ORGANISME', 'PRISE DE SERVICE', 'SITUATION',
       'DATE DEBUT SITUATION', 'EMPLOI', 'FONCTION', 'GRADE', 'CLASSE/ECHELON',
       'MONTANT BRUT', 'MONTANT NET', 'RETENUE  PENSION', 'IMPOT ',
       'CHARGE PATRONALE', 'MOIS/ANNEE', 'GRADE 2', 'AGE RETRAITE',
       'DATE RETRAITE', 'PERIODE', 'DATE_COLLECTE', 'CODE_ORGANISME',
       'ANNEE_NAISSANCE', 'MOIS_NAISSANCE', 'JOUR_NAISSANCE', 'ANNEE_COLLECTE',
       'MOIS_COLLECTE', 'JOUR_COLLECTE', 'nbre_date_naissances',
       'DATE_NAISSANCE_CORRIGEE', 'ANNEE_NAISSANCE_CORRIGEE',
       'MOIS_NAISSANCE_CORRIGEE', 'JOUR_NAISSANCE_CORRIGEE', 'AGE',
       'AGE_VALIDE', 'SEXE_VALIDE', 'AGE_IMPUTE',
       'SITUATION_MATRIMONIALE_RECODE', 'NBRE_ENFTS_IMPUTE', 'FONCTION_NORM',
       'LIBELLÉ_FONCTION_NORM', 'CODE_FONCTION', 'CODE_FONCTION_BEFORE',
       'SERVICE_NORM', 'LIBELLÉ_SERVICE_NORM', 'CODE_SERVICE',
       'CODE_SERVICE_BEFORE'],
      dtype='object')

**Paramètres**

In [83]:
nm_feuille = "ORGANISME" # nom de la feuille 
var_code_ext = "ID_ORGANISME"
var_lib_ext  = "LIBELLÉ_ORGANISME"
var_cle_ext  = var_lib_ext

var_cle_panel  = "ORGANISME"
var_code_panel = "ID_ORGANISME"
var_lib_panel  = "ORGANISME"


# Noms normalisés
var_norm_ext   = f"{var_cle_ext}_NORM"
var_norm_panel = f"{var_cle_panel}_NORM"

**1) Vérification**

In [84]:
_ = check_code_to_label_uniqueness(df_ref, var_code_ext, var_lib_ext)
var_norm_ext = ensure_normalized_column(df_ref, var_lib_ext, var_norm_ext)
_ = detect_normalized_duplicates(df_ref, var_norm_ext)

✅ Chaque code est associé à un seul libellé.
❌ Doublons détectés (normalisés) : 4 libellés en double.

**2) Mapping aléatoire (1 code / clé) + export dans un classeur commun**

In [85]:

mapping = build_random_mapping(df_ref, var_norm_ext, var_code_ext, var_lib_ext, seed=123)
export_mapping(mapping, workbook_path="Referentiels_unifies.xlsx", sheet_name= nm_feuille)

/tmp/ipykernel_26/2242558500.py:23: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.sample(n=1, random_state=seed))

✅ Feuille écrite : ORGANISME → Referentiels_unifies.xlsx

**3) Fusion dans le panel (panel_solde_df)**

In [86]:
panel_solde_df, _, _ = merge_mapping_into_panel(
    panel_solde_df, mapping,
    var_norm_panel=var_norm_panel, var_norm_ext=var_norm_ext,
    var_code_panel=var_code_panel, var_code_ext=var_code_ext,
    var_lib_panel=var_lib_panel )

Codes renseignés dans ID_ORGANISME : 15585123
Codes manquants dans ID_ORGANISME : 42840

**4) Similarité pour les non appariés (top 1 par clé)**

In [87]:
suggestions_best = best_suggestions(
    panel_solde_df, mapping,
    var_norm_panel=var_norm_panel, var_norm_ext=var_norm_ext,
    var_lib_ext=var_lib_ext, var_code_ext=var_code_ext,
    var_code_panel=var_code_panel,
    min_score_show=0
)

,ORGANISME_NORM_NON_APPARIE,MATCH_LIBELLÉ_ORGANISME_NORM,MATCH_SCORE,LIBELLÉ_ORGANISME,ID_ORGANISME
0,"min des mines, du petrole et de l energie","min des mines , du petrole et de l energie",98,"Min. des Mines , du petrole et de l Energie",14
1,"min delegue aupres du mae, charge int af et iv...","min delegue aupres du pm, charge des sports et...",71,"Min. délégué aupres du PM, chargé des sports e...",29

**5a)Application MANUELLE (tu fournis tes choix)**

In [88]:

CHOIX_FORCES = {
    # "cle_norm_panel_exemple": "CODE_CHOISI"
    "min des mines, du petrole et de l energie": "14"
}
panel_solde_df, audit_manuel = apply_choices(
    panel_solde_df,
    var_code_panel=var_code_panel, var_norm_panel=var_norm_panel,
    choices_map=CHOIX_FORCES,
    var_cle_panel=var_cle_panel, var_lib_panel=var_lib_panel
)

✔ Lignes mises à jour : 37766

**5b) OU Application AUTO par score (≥ 70 par défaut)**

In [89]:

panel_solde_df, audit_auto = auto_apply_by_score(
    panel_solde_df, suggestions_best,
    var_code_panel=var_code_panel, var_norm_panel=var_norm_panel,
    var_cle_panel=var_cle_panel, var_lib_panel=var_lib_panel,
    var_code_ext=var_code_ext, min_score=70
)

KeyboardInterrupt:

**6a) Enrichir le mapping avec les choix retenus (manuel)**

In [90]:
#   Ici on prend les choix AUTO comme exemple :
#   on reconstruit le dict choices_map à partir d'audit_auto
if not audit_manuel.empty:
    choices_map_manuel = dict(zip(
        panel_solde_df.loc[audit_manuel.index, var_norm_panel],
        panel_solde_df.loc[audit_manuel.index, var_code_panel]
    ))
else:
    choices_map_manuel = {}

mapping = enrich_mapping_with_choices(
    mapping_final=mapping,
    suggestions_best=suggestions_best,
    var_norm_panel=var_norm_panel,
    var_norm_ext=var_norm_ext, var_code_ext=var_code_ext, var_lib_ext=var_lib_ext,
    choices_map=choices_map_manuel
)

🔁 Mapping enrichi : +1 lignes (net).

**6b) Enrichir le mapping avec les choix retenus (auto)**

In [ ]:
#   Ici on prend les choix AUTO comme exemple :
#   on reconstruit le dict choices_map à partir d'audit_auto
if not audit_auto.empty:
    choices_map_auto = dict(zip(
        panel_solde_df.loc[audit_auto.index, var_norm_panel],
        panel_solde_df.loc[audit_auto.index, var_code_panel]
    ))
else:
    choices_map_auto = {}

mapping = enrich_mapping_with_choices(
    mapping_final=mapping,
    suggestions_best=suggestions_best,
    var_norm_panel=var_norm_panel,
    var_norm_ext=var_norm_ext, var_code_ext=var_code_ext, var_lib_ext=var_lib_ext,
    choices_map=choices_map_auto
)

In [ ]:

# (Option) réécrire la feuille “FONCTION” avec le mapping enrichi
export_mapping(mapping, workbook_path="Referentiels_unifies.xlsx", sheet_name="FONCTION")

In [23]:
xlsx = pd.ExcelFile(bytes_io)
print("Feuilles disponibles :", xlsx.sheet_names)

Feuilles disponibles : ['lieu affectation', 'ORGANISME_OK', 'CODE_SITUATION_SOLDE', 'HISTORIQUE_ECHELLES_CORPS', 'ECHELLES_CORPS_ACTUEL', 'service', 'FONCTION', 'grade']

## 4.Ajout des codes de ECHELONS dans la base de travaiL

**Chargement**

* Fichier code

In [91]:
fichier_ref = "grade"
df_ref = read_reference(bytes_io, fichier_ref)

=== grade | APERÇU BRUT (top 5) ===

  CODE_GRADE                       LIBELLÉ_GRADE
0         10                           Militaire
1         11   Classe Exceptionnelle 1er Echelon
2         12  Classe Exceptionnelle 2ème Echelon
3         13  Classe Exceptionnelle 3ème Echelon
4         15                           Militaire

Colonnes BRUTES (grade) : ['CODE_GRADE', 'LIBELLÉ_GRADE']
Shape brut : (278, 2)

=== grade | APRÈS NETTOYAGE (top 5) ===

  CODE_GRADE                       LIBELLÉ_GRADE
0         10                           Militaire
1         11   Classe Exceptionnelle 1er Echelon
2         12  Classe Exceptionnelle 2ème Echelon
3         13  Classe Exceptionnelle 3ème Echelon
4         15                           Militaire

Colonnes NETTOYÉES (grade) : ['CODE_GRADE', 'LIBELLÉ_GRADE']
Shape nettoyé : (278, 2)

* Base de travail

In [19]:
panel_solde_df.columns

Index(['MATRICULE||CODE_ORGANISME', 'MATRICULE', 'NOM', 'DATE NAISSANCE',
       'SEXE', 'SITUATION MATRIMONIALE', 'NOMBRE ENFANT', 'LIEU AFFECTATION',
       'SERVICE', 'ORGANISME', 'PRISE DE SERVICE', 'SITUATION',
       'DATE DEBUT SITUATION', 'EMPLOI', 'FONCTION', 'GRADE', 'CLASSE/ECHELON',
       'MONTANT BRUT', 'MONTANT NET', 'RETENUE  PENSION', 'IMPOT ',
       'CHARGE PATRONALE', 'MOIS/ANNEE', 'GRADE 2', 'AGE RETRAITE',
       'DATE RETRAITE', 'PERIODE', 'DATE_COLLECTE', 'CODE_ORGANISME',
       'ANNEE_NAISSANCE', 'MOIS_NAISSANCE', 'JOUR_NAISSANCE', 'ANNEE_COLLECTE',
       'MOIS_COLLECTE', 'JOUR_COLLECTE', 'nbre_date_naissances',
       'DATE_NAISSANCE_CORRIGEE', 'ANNEE_NAISSANCE_CORRIGEE',
       'MOIS_NAISSANCE_CORRIGEE', 'JOUR_NAISSANCE_CORRIGEE', 'AGE',
       'AGE_VALIDE', 'SEXE_VALIDE', 'AGE_IMPUTE',
       'SITUATION_MATRIMONIALE_RECODE', 'NBRE_ENFTS_IMPUTE'],
      dtype='object')

**Paramètres**

In [92]:
nm_feuille = "ECHELONS" # nom de la feuille 
var_code_ext = "CODE_GRADE"
var_lib_ext  = "LIBELLÉ_GRADE"
var_cle_ext  = var_lib_ext

var_cle_panel  = "CLASSE/ECHELON"
var_code_panel = "CODE_GRADE"
var_lib_panel  = "CLASSE/ECHELON"


# Noms normalisés
var_norm_ext   = f"{var_cle_ext}_NORM"
var_norm_panel = f"{var_cle_panel}_NORM"

**1) Vérification**

In [93]:
_ = check_code_to_label_uniqueness(df_ref, var_code_ext, var_lib_ext)
var_norm_ext = ensure_normalized_column(df_ref, var_lib_ext, var_norm_ext)
_ = detect_normalized_duplicates(df_ref, var_norm_ext)

✅ Chaque code est associé à un seul libellé.
❌ Doublons détectés (normalisés) : 8 libellés en double.

**2) Mapping aléatoire (1 code / clé) + export dans un classeur commun**

In [94]:

mapping = build_random_mapping(df_ref, var_norm_ext, var_code_ext, var_lib_ext, seed=123)
export_mapping(mapping, workbook_path="Referentiels_unifies.xlsx", sheet_name= nm_feuille)

/tmp/ipykernel_26/2242558500.py:23: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.sample(n=1, random_state=seed))

✅ Feuille écrite : ECHELONS → Referentiels_unifies.xlsx

**3) Fusion dans le panel (panel_solde_df)**

In [95]:
panel_solde_df, _, _ = merge_mapping_into_panel(
    panel_solde_df, mapping,
    var_norm_panel=var_norm_panel, var_norm_ext=var_norm_ext,
    var_code_panel=var_code_panel, var_code_ext=var_code_ext,
    var_lib_panel=var_lib_panel
)

Codes renseignés dans CODE_GRADE : 15310507
Codes manquants dans CODE_GRADE : 317456

**4) Similarité pour les non appariés (top 1 par clé)**

In [96]:
suggestions_best = best_suggestions(
    panel_solde_df, mapping,
    var_norm_panel=var_norm_panel, var_norm_ext=var_norm_ext,
    var_lib_ext=var_lib_ext, var_code_ext=var_code_ext,
    var_code_panel=var_code_panel,
    min_score_show=0
)

,CLASSE/ECHELON_NORM_NON_APPARIE,MATCH_LIBELLÉ_GRADE_NORM,MATCH_SCORE,LIBELLÉ_GRADE,CODE_GRADE
0,sous officier eleve 1ere annee,sous officier eleve 1ere annee,100,Sous-Officier éléve 1ère année,NaN
1,insp general 1er ech,insp general 1er ch,97,Insp. Général 1er ch,I1
2,adm general 2eme ech,adm general 1er ech,87,Adm. Général 1er ech,A2

**5a)Application MANUELLE (tu fournis tes choix)**

In [97]:

CHOIX_FORCES = {
    # "cle_norm_panel_exemple": "CODE_CHOISI"
    "insp general 1er ech": "I1"
}
panel_solde_df, audit_manuel = apply_choices(
    panel_solde_df,
    var_code_panel=var_code_panel, var_norm_panel=var_norm_panel,
    choices_map=CHOIX_FORCES,
    var_cle_panel=var_cle_panel, var_lib_panel=var_lib_panel
)

✔ Lignes mises à jour : 90

**5b) OU Application AUTO par score (≥ 70 par défaut)**

In [27]:

panel_solde_df, audit_auto = auto_apply_by_score(
    panel_solde_df, suggestions_best,
    var_code_panel=var_code_panel, var_norm_panel=var_norm_panel,
    var_cle_panel=var_cle_panel, var_lib_panel=var_lib_panel,
    var_code_ext=var_code_ext, min_score=70
)

✔ Lignes mises à jour : 72

**6a) Enrichir le mapping avec les choix retenus (manuel)**

In [98]:
#   Ici on prend les choix AUTO comme exemple :
#   on reconstruit le dict choices_map à partir d'audit_auto
if not audit_manuel.empty:
    choices_map_manuel = dict(zip(
        panel_solde_df.loc[audit_manuel.index, var_norm_panel],
        panel_solde_df.loc[audit_manuel.index, var_code_panel]
    ))
else:
    choices_map_manuel = {}

mapping = enrich_mapping_with_choices(
    mapping_final=mapping,
    suggestions_best=suggestions_best,
    var_norm_panel=var_norm_panel,
    var_norm_ext=var_norm_ext, var_code_ext=var_code_ext, var_lib_ext=var_lib_ext,
    choices_map=choices_map_manuel
)

🔁 Mapping enrichi : +-1 lignes (net).

**6b) Enrichir le mapping avec les choix retenus (auto)**

In [ ]:
#   Ici on prend les choix AUTO comme exemple :
#   on reconstruit le dict choices_map à partir d'audit_auto
if not audit_auto.empty:
    choices_map_auto = dict(zip(
        panel_solde_df.loc[audit_auto.index, var_norm_panel],
        panel_solde_df.loc[audit_auto.index, var_code_panel]
    ))
else:
    choices_map_auto = {}

mapping = enrich_mapping_with_choices(
    mapping_final=mapping,
    suggestions_best=suggestions_best,
    var_norm_panel=var_norm_panel,
    var_norm_ext=var_norm_ext, var_code_ext=var_code_ext, var_lib_ext=var_lib_ext,
    choices_map=choices_map_auto
)

In [ ]:

# (Option) réécrire la feuille “FONCTION” avec le mapping enrichi
export_mapping(mapping, workbook_path="Referentiels_unifies.xlsx", sheet_name="FONCTION")

In [23]:
xlsx = pd.ExcelFile(bytes_io)
print("Feuilles disponibles :", xlsx.sheet_names)

Feuilles disponibles : ['lieu affectation', 'ORGANISME_OK', 'CODE_SITUATION_SOLDE', 'HISTORIQUE_ECHELLES_CORPS', 'ECHELLES_CORPS_ACTUEL', 'service', 'FONCTION', 'grade']

## 5.Ajout des codes de EMPLOIS dans la base de travail

**Chargement**

* Fichier code

In [99]:
fichier_ref = "HISTORIQUE_ECHELLES_CORPS"
df_ref = read_reference(bytes_io, fichier_ref)

=== HISTORIQUE_ECHELLES_CORPS | APERÇU BRUT (top 5) ===

,TABLEAU: LISTE EXHAUSTIVE DES CODIFICATIONS DES EMPLOIS DANS LA BASE DE DONNEES DE LA DIRECTION DE LA SOLDE,Unnamed: 1,Unnamed: 2
0,NaN,NaN,NaN
1,NaN,NaN,NaN
2,CODE_EMPLOI,LIBELLÉ_EMPLOI,GRADE_ADMINISTRATIF_ASSOCIE
3,C1AG,Assistant des Greffes et Parquets,C3
4,A2TE,Ingénieur des Techn. d'Elevage,A3

Colonnes BRUTES (HISTORIQUE_ECHELLES_CORPS) : ['TABLEAU: LISTE EXHAUSTIVE DES CODIFICATIONS  DES EMPLOIS DANS LA BASE DE DONNEES DE LA DIRECTION DE LA SOLDE', 'Unnamed: 1', 'Unnamed: 2']
Shape brut : (1258, 3)

=== HISTORIQUE_ECHELLES_CORPS | APRÈS NETTOYAGE (top 5) ===

,CODE_EMPLOI,LIBELLÉ_EMPLOI,GRADE_ADMINISTRATIF_ASSOCIE
0,C1AG,Assistant des Greffes et Parquets,C3
1,A2TE,Ingénieur des Techn. d'Elevage,A3
2,22I1,Inspec. Général: Educ. et Formation,A7
3,22I2,Inspec. Général: Ensgt Art. et Culturel,A7
4,22I3,Inspec. Général: Ensgt sous Sect. Social,A7

Colonnes NETTOYÉES (HISTORIQUE_ECHELLES_CORPS) : ['CODE_EMPLOI', 'LIBELLÉ_EMPLOI', 'GRADE_ADMINISTRATIF_ASSOCIE']
Shape nettoyé : (1255, 3)

* Base de travail

In [19]:
panel_solde_df.columns

Index(['MATRICULE||CODE_ORGANISME', 'MATRICULE', 'NOM', 'DATE NAISSANCE',
       'SEXE', 'SITUATION MATRIMONIALE', 'NOMBRE ENFANT', 'LIEU AFFECTATION',
       'SERVICE', 'ORGANISME', 'PRISE DE SERVICE', 'SITUATION',
       'DATE DEBUT SITUATION', 'EMPLOI', 'FONCTION', 'GRADE', 'CLASSE/ECHELON',
       'MONTANT BRUT', 'MONTANT NET', 'RETENUE  PENSION', 'IMPOT ',
       'CHARGE PATRONALE', 'MOIS/ANNEE', 'GRADE 2', 'AGE RETRAITE',
       'DATE RETRAITE', 'PERIODE', 'DATE_COLLECTE', 'CODE_ORGANISME',
       'ANNEE_NAISSANCE', 'MOIS_NAISSANCE', 'JOUR_NAISSANCE', 'ANNEE_COLLECTE',
       'MOIS_COLLECTE', 'JOUR_COLLECTE', 'nbre_date_naissances',
       'DATE_NAISSANCE_CORRIGEE', 'ANNEE_NAISSANCE_CORRIGEE',
       'MOIS_NAISSANCE_CORRIGEE', 'JOUR_NAISSANCE_CORRIGEE', 'AGE',
       'AGE_VALIDE', 'SEXE_VALIDE', 'AGE_IMPUTE',
       'SITUATION_MATRIMONIALE_RECODE', 'NBRE_ENFTS_IMPUTE'],
      dtype='object')

**Paramètres**

In [100]:
nm_feuille = "EMPLOIS" # nom de la feuille 
var_code_ext = "CODE_EMPLOI"
var_lib_ext  = "LIBELLÉ_EMPLOI"
var_cle_ext  = var_lib_ext

var_cle_panel  = "EMPLOI"
var_code_panel = "CODE_EMPLOI"
var_lib_panel  = "EMPLOI"


# Noms normalisés
var_norm_ext   = f"{var_cle_ext}_NORM"
var_norm_panel = f"{var_cle_panel}_NORM"

**1) Vérification**

In [101]:
_ = check_code_to_label_uniqueness(df_ref, var_code_ext, var_lib_ext)
var_norm_ext = ensure_normalized_column(df_ref, var_lib_ext, var_norm_ext)
_ = detect_normalized_duplicates(df_ref, var_norm_ext)

✅ Chaque code est associé à un seul libellé.
❌ Doublons détectés (normalisés) : 341 libellés en double.

**2) Mapping aléatoire (1 code / clé) + export dans un classeur commun**

In [102]:

mapping = build_random_mapping(df_ref, var_norm_ext, var_code_ext, var_lib_ext, seed=123)
export_mapping(mapping, workbook_path="Referentiels_unifies.xlsx", sheet_name= nm_feuille)

/tmp/ipykernel_26/2242558500.py:23: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.sample(n=1, random_state=seed))

✅ Feuille écrite : EMPLOIS → Referentiels_unifies.xlsx

**3) Fusion dans le panel (panel_solde_df)**

In [103]:
panel_solde_df, _, _ = merge_mapping_into_panel(
    panel_solde_df, mapping,
    var_norm_panel=var_norm_panel, var_norm_ext=var_norm_ext,
    var_code_panel=var_code_panel, var_code_ext=var_code_ext,
    var_lib_panel=var_lib_panel
)

Codes renseignés dans CODE_EMPLOI : 15312585
Codes manquants dans CODE_EMPLOI : 315378

**4) Similarité pour les non appariés (top 1 par clé)**

In [104]:
suggestions_best = best_suggestions(
    panel_solde_df, mapping,
    var_norm_panel=var_norm_panel, var_norm_ext=var_norm_ext,
    var_lib_ext=var_lib_ext, var_code_ext=var_code_ext,
    var_code_panel=var_code_panel,
    min_score_show=0
)

Empty DataFrame
Columns: [EMPLOI_NORM_NON_APPARIE, MATCH_LIBELLÉ_EMPLOI_NORM, MATCH_SCORE, LIBELLÉ_EMPLOI, CODE_EMPLOI]
Index: []

**5a)Application MANUELLE (tu fournis tes choix)**

In [ ]:

CHOIX_FORCES = {
    # "cle_norm_panel_exemple": "CODE_CHOISI"
    # ex: "tresorier charge d etudes g4": "797"
}
panel_solde_df, audit_manuel = apply_choices(
    panel_solde_df,
    var_code_panel=var_code_panel, var_norm_panel=var_norm_panel,
    choices_map=CHOIX_FORCES,
    var_cle_panel=var_cle_panel, var_lib_panel=var_lib_panel
)

**5b) OU Application AUTO par score (≥ 70 par défaut)**

In [27]:

panel_solde_df, audit_auto = auto_apply_by_score(
    panel_solde_df, suggestions_best,
    var_code_panel=var_code_panel, var_norm_panel=var_norm_panel,
    var_cle_panel=var_cle_panel, var_lib_panel=var_lib_panel,
    var_code_ext=var_code_ext, min_score=70
)

✔ Lignes mises à jour : 72

**6a) Enrichir le mapping avec les choix retenus (manuel)**

In [44]:
#   Ici on prend les choix AUTO comme exemple :
#   on reconstruit le dict choices_map à partir d'audit_auto
if not audit_manuel.empty:
    choices_map_manuel = dict(zip(
        panel_solde_df.loc[audit_manuel.index, var_norm_panel],
        panel_solde_df.loc[audit_manuel.index, var_code_panel]
    ))
else:
    choices_map_manuel = {}

mapping = enrich_mapping_with_choices(
    mapping_final=mapping,
    suggestions_best=suggestions_best,
    var_norm_panel=var_norm_panel,
    var_norm_ext=var_norm_ext, var_code_ext=var_code_ext, var_lib_ext=var_lib_ext,
    choices_map=choices_map_manuel
)

🔁 Mapping enrichi : +0 lignes (net).

**6b) Enrichir le mapping avec les choix retenus (auto)**

In [ ]:
#   Ici on prend les choix AUTO comme exemple :
#   on reconstruit le dict choices_map à partir d'audit_auto
if not audit_auto.empty:
    choices_map_auto = dict(zip(
        panel_solde_df.loc[audit_auto.index, var_norm_panel],
        panel_solde_df.loc[audit_auto.index, var_code_panel]
    ))
else:
    choices_map_auto = {}

mapping = enrich_mapping_with_choices(
    mapping_final=mapping,
    suggestions_best=suggestions_best,
    var_norm_panel=var_norm_panel,
    var_norm_ext=var_norm_ext, var_code_ext=var_code_ext, var_lib_ext=var_lib_ext,
    choices_map=choices_map_auto
)

In [ ]:

# (Option) réécrire la feuille “FONCTION” avec le mapping enrichi
export_mapping(mapping, workbook_path="Referentiels_unifies.xlsx", sheet_name="FONCTION")

In [23]:
xlsx = pd.ExcelFile(bytes_io)
print("Feuilles disponibles :", xlsx.sheet_names)

Feuilles disponibles : ['lieu affectation', 'ORGANISME_OK', 'CODE_SITUATION_SOLDE', 'HISTORIQUE_ECHELLES_CORPS', 'ECHELLES_CORPS_ACTUEL', 'service', 'FONCTION', 'grade']

## 6.Ajout des codes de STATUT D'ACTIVITE dans la base de travail

**Chargement**

* Fichier code

In [105]:
fichier_ref = "CODE_SITUATION_SOLDE"
df_ref = read_reference(bytes_io, fichier_ref)

=== CODE_SITUATION_SOLDE | APERÇU BRUT (top 5) ===

   CODE_POSITION_SOLDE LIBELLÉ_POSITION_SOLDE ( LIBELLE_SITUATION_SOLDE)
0                    0                                            Annulé
1                    1                          Prise En Compte En Cours
2                    9                    Agent en Liquidation de Droits
3                   10                                       En Activité
4                   20                               Suspendu Sans Solde

Colonnes BRUTES (CODE_SITUATION_SOLDE) : ['CODE_POSITION_SOLDE', 'LIBELLÉ_POSITION_SOLDE ( LIBELLE_SITUATION_SOLDE)']
Shape brut : (60, 2)

=== CODE_SITUATION_SOLDE | APRÈS NETTOYAGE (top 5) ===

   CODE_POSITION_SOLDE LIBELLÉ_POSITION_SOLDE ( LIBELLE_SITUATION_SOLDE)
0                    0                                            Annulé
1                    1                          Prise En Compte En Cours
2                    9                    Agent en Liquidation de Droits
3                   10                                       En Activité
4                   20                               Suspendu Sans Solde

Colonnes NETTOYÉES (CODE_SITUATION_SOLDE) : ['CODE_POSITION_SOLDE', 'LIBELLÉ_POSITION_SOLDE ( LIBELLE_SITUATION_SOLDE)']
Shape nettoyé : (60, 2)

* Base de travail

In [106]:
panel_solde_df.columns

Index(['MATRICULE||CODE_ORGANISME', 'MATRICULE', 'NOM', 'DATE NAISSANCE',
       'SEXE', 'SITUATION MATRIMONIALE', 'NOMBRE ENFANT', 'LIEU AFFECTATION',
       'SERVICE', 'ORGANISME', 'PRISE DE SERVICE', 'SITUATION',
       'DATE DEBUT SITUATION', 'EMPLOI', 'FONCTION', 'GRADE', 'CLASSE/ECHELON',
       'MONTANT BRUT', 'MONTANT NET', 'RETENUE  PENSION', 'IMPOT ',
       'CHARGE PATRONALE', 'MOIS/ANNEE', 'GRADE 2', 'AGE RETRAITE',
       'DATE RETRAITE', 'PERIODE', 'DATE_COLLECTE', 'CODE_ORGANISME',
       'ANNEE_NAISSANCE', 'MOIS_NAISSANCE', 'JOUR_NAISSANCE', 'ANNEE_COLLECTE',
       'MOIS_COLLECTE', 'JOUR_COLLECTE', 'nbre_date_naissances',
       'DATE_NAISSANCE_CORRIGEE', 'ANNEE_NAISSANCE_CORRIGEE',
       'MOIS_NAISSANCE_CORRIGEE', 'JOUR_NAISSANCE_CORRIGEE', 'AGE',
       'AGE_VALIDE', 'SEXE_VALIDE', 'AGE_IMPUTE',
       'SITUATION_MATRIMONIALE_RECODE', 'NBRE_ENFTS_IMPUTE', 'FONCTION_NORM',
       'LIBELLÉ_FONCTION_NORM', 'CODE_FONCTION', 'CODE_FONCTION_BEFORE',
       'SERVICE_NORM', 'LIBELLÉ_SERVICE_NORM', 'CODE_SERVICE',
       'CODE_SERVICE_BEFORE', 'ORGANISME_NORM', 'LIBELLÉ_ORGANISME_NORM',
       'ID_ORGANISME', 'ID_ORGANISME_BEFORE', 'CLASSE/ECHELON_NORM',
       'LIBELLÉ_GRADE_NORM', 'CODE_GRADE', 'CODE_GRADE_BEFORE', 'EMPLOI_NORM',
       'LIBELLÉ_EMPLOI_NORM', 'CODE_EMPLOI'],
      dtype='object')

**Paramètres**

In [107]:
nm_feuille = "STATUT_ACTIVITE" # nom de la feuille 
var_code_ext = "CODE_POSITION_SOLDE"
var_lib_ext  = "LIBELLÉ_POSITION_SOLDE ( LIBELLE_SITUATION_SOLDE)"
var_cle_ext  = var_lib_ext

var_cle_panel  = "SITUATION"
var_code_panel = "CODE_POSITION_SOLDE"
var_lib_panel  = "SITUATION"


# Noms normalisés
var_norm_ext   = f"{var_cle_ext}_NORM"
var_norm_panel = f"{var_cle_panel}_NORM"

**1) Vérification**

In [108]:
_ = check_code_to_label_uniqueness(df_ref, var_code_ext, var_lib_ext)
var_norm_ext = ensure_normalized_column(df_ref, var_lib_ext, var_norm_ext)
_ = detect_normalized_duplicates(df_ref, var_norm_ext)

✅ Chaque code est associé à un seul libellé.
✅ Aucun doublon détecté (normalisation).

**2) Mapping aléatoire (1 code / clé) + export dans un classeur commun**

In [109]:

mapping = build_random_mapping(df_ref, var_norm_ext, var_code_ext, var_lib_ext, seed=123)
export_mapping(mapping, workbook_path="Referentiels_unifies.xlsx", sheet_name= nm_feuille)

/tmp/ipykernel_26/2242558500.py:23: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.sample(n=1, random_state=seed))

✅ Feuille écrite : STATUT_ACTIVITE → Referentiels_unifies.xlsx

**3) Fusion dans le panel (panel_solde_df)**

In [110]:
panel_solde_df, _, _ = merge_mapping_into_panel(
    panel_solde_df, mapping,
    var_norm_panel=var_norm_panel, var_norm_ext=var_norm_ext,
    var_code_panel=var_code_panel, var_code_ext=var_code_ext,
    var_lib_panel=var_lib_panel
)

Codes renseignés dans CODE_POSITION_SOLDE : 15627963
Codes manquants dans CODE_POSITION_SOLDE : 0

**4) Similarité pour les non appariés (top 1 par clé)**

In [111]:
suggestions_best = best_suggestions(
    panel_solde_df, mapping,
    var_norm_panel=var_norm_panel, var_norm_ext=var_norm_ext,
    var_lib_ext=var_lib_ext, var_code_ext=var_code_ext,
    var_code_panel=var_code_panel,
    min_score_show=0
)

Empty DataFrame
Columns: [SITUATION_NORM_NON_APPARIE, MATCH_LIBELLÉ_POSITION_SOLDE ( LIBELLE_SITUATION_SOLDE)_NORM, MATCH_SCORE, LIBELLÉ_POSITION_SOLDE ( LIBELLE_SITUATION_SOLDE), CODE_POSITION_SOLDE]
Index: []

**5a)Application MANUELLE (tu fournis tes choix)**

In [ ]:

CHOIX_FORCES = {
    # "cle_norm_panel_exemple": "CODE_CHOISI"
    # ex: "tresorier charge d etudes g4": "797"
}
panel_solde_df, audit_manuel = apply_choices(
    panel_solde_df,
    var_code_panel=var_code_panel, var_norm_panel=var_norm_panel,
    choices_map=CHOIX_FORCES,
    var_cle_panel=var_cle_panel, var_lib_panel=var_lib_panel
)

**5b) OU Application AUTO par score (≥ 70 par défaut)**

In [27]:

panel_solde_df, audit_auto = auto_apply_by_score(
    panel_solde_df, suggestions_best,
    var_code_panel=var_code_panel, var_norm_panel=var_norm_panel,
    var_cle_panel=var_cle_panel, var_lib_panel=var_lib_panel,
    var_code_ext=var_code_ext, min_score=70
)

✔ Lignes mises à jour : 72

**6a) Enrichir le mapping avec les choix retenus (manuel)**

In [44]:
#   Ici on prend les choix AUTO comme exemple :
#   on reconstruit le dict choices_map à partir d'audit_auto
if not audit_manuel.empty:
    choices_map_manuel = dict(zip(
        panel_solde_df.loc[audit_manuel.index, var_norm_panel],
        panel_solde_df.loc[audit_manuel.index, var_code_panel]
    ))
else:
    choices_map_manuel = {}

mapping = enrich_mapping_with_choices(
    mapping_final=mapping,
    suggestions_best=suggestions_best,
    var_norm_panel=var_norm_panel,
    var_norm_ext=var_norm_ext, var_code_ext=var_code_ext, var_lib_ext=var_lib_ext,
    choices_map=choices_map_manuel
)

🔁 Mapping enrichi : +0 lignes (net).

**6b) Enrichir le mapping avec les choix retenus (auto)**

In [ ]:
#   Ici on prend les choix AUTO comme exemple :
#   on reconstruit le dict choices_map à partir d'audit_auto
if not audit_auto.empty:
    choices_map_auto = dict(zip(
        panel_solde_df.loc[audit_auto.index, var_norm_panel],
        panel_solde_df.loc[audit_auto.index, var_code_panel]
    ))
else:
    choices_map_auto = {}

mapping = enrich_mapping_with_choices(
    mapping_final=mapping,
    suggestions_best=suggestions_best,
    var_norm_panel=var_norm_panel,
    var_norm_ext=var_norm_ext, var_code_ext=var_code_ext, var_lib_ext=var_lib_ext,
    choices_map=choices_map_auto
)

In [ ]:

# (Option) réécrire la feuille “FONCTION” avec le mapping enrichi
export_mapping(mapping, workbook_path="Referentiels_unifies.xlsx", sheet_name="FONCTION")