# 🔍 Vérification ANSTAT vs Indicateurs Salaire Brut 2024-2025

**Objectif** : Comparer les min/max par **Grade** et par **Barème / Grille salariale** entre :
- Le fichier de référence `anstat_2025.txt.xlsx` (grille salariale théorique)
- Le fichier `indicateurs_salaire_brut_2024_2025_avec_zeros_SOMMAIRE_200426.xlsx` (indicateurs calculés sur données réelles)

**Étapes** :
1. Charger `anstat_2025.txt.xlsx` et créer la colonne `Montant brut sans indemnités`
2. Calculer les min/max par Grade et par Barème depuis ANSTAT
3. Charger les indicateurs (feuilles GRADE_* et BAREME_G_*)
4. Comparer les bornes et identifier les écarts

## 📦 1. Imports et configuration

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Chemins des fichiers
PATH_ANSTAT = "anstat_2025.txt.xlsx"
PATH_INDICATEURS = "indicateurs_salaire_brut_2024_2025_avec_zeros_SOMMAIRE_200426.xlsx"

print("✅ Imports OK")

✅ Imports OK

## 📂 2. Chargement de `anstat_2025.txt.xlsx`

In [2]:
df_anstat = pd.read_excel(PATH_ANSTAT)
print(f"✅ ANSTAT chargé : {df_anstat.shape[0]} lignes × {df_anstat.shape[1]} colonnes")
print(f"\nColonnes : {df_anstat.columns.tolist()}")
print(f"\nSECTEURS uniques : {df_anstat['SECTEUR'].unique().tolist()}")
print(f"\nGRADES uniques   : {df_anstat['GRADE'].unique().tolist()}")
df_anstat.head(3)

✅ ANSTAT chargé : 754 lignes × 18 colonnes

Colonnes : ['SECTEUR', 'CATEGORIE', 'GRADE', 'INDICE', 'ECHELON/CLASSE', 'Salaire de Base', 'Résidence', 'Logement', 'Transport', 'Allocations\n (2 enfants)', 'AUTRES INDEMNITES', 'Montant brut', 'Charge patronale', 'ITS', 'PENSION', 'MUGEF-CI/CMU', 'NET', 'BASE IMPOSABLE']

SECTEURS uniques : ['Barême Général', 'Informaticien', 'Tech-Santé', 'Cadre-Sup-Santé', 'ENS SEC & PRIM', 'ENS SUP', 'SECRETAIRE DIRECTION', 'GREFFE', 'MAGISTRAT ', 'CORPS PREF', 'CORPS DIPL', 'para militaire']

GRADES uniques   : ['A7', 'A6', 'A5', 'A4', 'A3', 'B3', 'B1', 'C3', 'C2', 'C1', 'D2', 'D1']

,SECTEUR,CATEGORIE,GRADE,INDICE,ECHELON/CLASSE,Salaire de Base,Résidence,Logement,Transport,Allocations\n (2 enfants),AUTRES INDEMNITES,Montant brut,Charge patronale,ITS,PENSION,MUGEF-CI/CMU,NET,BASE IMPOSABLE
0,Barême Général,A,A7,2350,21,548621.60,82293.240,90000,15000,15000,NaN,750914.840,91455.220720,91992.11640,45700.179280,7004.0,606218.544320,630914.840
1,Barême Général,A,A7,2295,33,535781.52,80367.228,90000,15000,15000,NaN,736148.748,89314.779384,88891.23708,44630.600616,7004.0,595622.910304,616148.748
2,Barême Général,A,A7,2255,32,526443.28,78966.492,90000,15000,15000,NaN,725409.772,87758.094776,86636.05212,43852.725224,7004.0,587916.994656,605409.772

## 🧮 3. Création de `Montant brut sans indemnités`

Formule : **Salaire de Base + Résidence + Logement + Transport + Allocations (2 enfants)**

*(On exclut les "AUTRES INDEMNITES" car elles varient selon le poste)*

In [3]:
# Colonnes composant le montant brut sans indemnités
cols_montant_brut_sans_indem = [
    "Salaire de Base",
    "Résidence",
    "Logement",
    "Transport",
    "Allocations\n (2 enfants)"
]

# Vérifier que toutes les colonnes existent
for c in cols_montant_brut_sans_indem:
    assert c in df_anstat.columns, f"Colonne manquante : '{c}'"

# Calculer le montant brut sans indemnités
df_anstat["Montant brut sans indemnités"] = df_anstat[cols_montant_brut_sans_indem].sum(axis=1)

# Réorganiser : insérer après AUTRES INDEMNITES
cols = list(df_anstat.columns)
cols.remove("Montant brut sans indemnités")
position = cols.index("AUTRES INDEMNITES") + 1
cols.insert(position, "Montant brut sans indemnités")
df_anstat = df_anstat[cols]

print("✅ Colonne 'Montant brut sans indemnités' créée avec succès")
print(f"\nExemples (5 premières lignes) :")
df_anstat[["SECTEUR", "GRADE", "Salaire de Base", "Résidence", "Logement", "Transport",
           "Allocations\n (2 enfants)", "AUTRES INDEMNITES", "Montant brut sans indemnités", "Montant brut"]].head()

✅ Colonne 'Montant brut sans indemnités' créée avec succès

Exemples (5 premières lignes) :

,SECTEUR,GRADE,Salaire de Base,Résidence,Logement,Transport,Allocations\n (2 enfants),AUTRES INDEMNITES,Montant brut sans indemnités,Montant brut
0,Barême Général,A7,548621.60,82293.240,90000,15000,15000,NaN,750914.840,750914.840
1,Barême Général,A7,535781.52,80367.228,90000,15000,15000,NaN,736148.748,736148.748
2,Barême Général,A7,526443.28,78966.492,90000,15000,15000,NaN,725409.772,725409.772
3,Barême Général,A7,506599.52,75989.928,90000,15000,15000,NaN,702589.448,702589.448
4,Barême Général,A7,498428.56,74764.284,90000,15000,15000,NaN,693192.844,693192.844

### Vérification de cohérence

In [4]:
# Vérifier : Montant brut = Montant brut sans indemnités + AUTRES INDEMNITES
df_anstat["AUTRES INDEMNITES_num"] = pd.to_numeric(df_anstat["AUTRES INDEMNITES"], errors='coerce').fillna(0)
df_anstat["check_montant"] = df_anstat["Montant brut sans indemnités"] + df_anstat["AUTRES INDEMNITES_num"]
df_anstat["diff_montant"] = abs(df_anstat["Montant brut"] - df_anstat["check_montant"])

ecarts = df_anstat[df_anstat["diff_montant"] > 0.01]
if len(ecarts) > 0:
    print(f"⚠️  {len(ecarts)} lignes avec un écart entre 'Montant brut' et 'Montant brut sans indemnités + AUTRES INDEMNITES'")
    print(ecarts[["SECTEUR", "GRADE", "Montant brut", "check_montant", "diff_montant"]].head(10))
else:
    print("✅ Cohérence vérifiée : Montant brut = Montant brut sans indemnités + AUTRES INDEMNITES")

# Nettoyage colonnes temporaires
df_anstat.drop(columns=["AUTRES INDEMNITES_num", "check_montant", "diff_montant"], inplace=True)

✅ Cohérence vérifiée : Montant brut = Montant brut sans indemnités + AUTRES INDEMNITES

### 💾 Export du fichier `montant_brut_sans_indemnites`

In [5]:
# Exporter le fichier montant_brut_sans_indemnites
df_export = df_anstat[["SECTEUR", "CATEGORIE", "GRADE", "INDICE", "ECHELON/CLASSE",
                       "Salaire de Base", "Résidence", "Logement", "Transport",
                       "Allocations\n (2 enfants)", "AUTRES INDEMNITES",
                       "Montant brut sans indemnités", "Montant brut"]].copy()

df_export.to_excel("montant_brut_sans_indemnites.xlsx", index=False)
print(f"✅ Fichier 'montant_brut_sans_indemnites.xlsx' exporté ({len(df_export)} lignes)")
df_export.head()

✅ Fichier 'montant_brut_sans_indemnites.xlsx' exporté (754 lignes)

,SECTEUR,CATEGORIE,GRADE,INDICE,ECHELON/CLASSE,Salaire de Base,Résidence,Logement,Transport,Allocations\n (2 enfants),AUTRES INDEMNITES,Montant brut sans indemnités,Montant brut
0,Barême Général,A,A7,2350,21,548621.60,82293.240,90000,15000,15000,NaN,750914.840,750914.840
1,Barême Général,A,A7,2295,33,535781.52,80367.228,90000,15000,15000,NaN,736148.748,736148.748
2,Barême Général,A,A7,2255,32,526443.28,78966.492,90000,15000,15000,NaN,725409.772,725409.772
3,Barême Général,A,A7,2170,31,506599.52,75989.928,90000,15000,15000,NaN,702589.448,702589.448
4,Barême Général,A,A7,2135,44,498428.56,74764.284,90000,15000,15000,NaN,693192.844,693192.844

## 📊 4. Calcul des bornes ANSTAT par Grade

On calcule le **min** et **max** de `Montant brut sans indemnités` pour chaque GRADE dans la grille ANSTAT.

In [6]:
# Min/Max par GRADE (tous secteurs confondus)
df_bornes_grade = (
    df_anstat
    .groupby("GRADE")
    .agg(
        ANSTAT_min=("Montant brut sans indemnités", "min"),
        ANSTAT_max=("Montant brut sans indemnités", "max"),
        ANSTAT_nb_echelons=("Montant brut sans indemnités", "count")
    )
    .reset_index()
    .sort_values("GRADE")
)

print("📋 Bornes ANSTAT par GRADE (Montant brut sans indemnités) :")
print("=" * 65)
df_bornes_grade

📋 Bornes ANSTAT par GRADE (Montant brut sans indemnités) :
=================================================================

   GRADE  ANSTAT_min   ANSTAT_max  ANSTAT_nb_echelons
0     A3  312833.752   761186.000                  90
1     A4  340284.588  1051606.168                 106
2     A5  379077.796  1109328.164                  88
3     A6  473043.836  1357666.984                  86
4     A7  646209.824  1461236.680                  86
5     B1  241688.036   338338.820                  39
6     B3  272562.592   557145.456                  90
7     C1  213498.224   275247.336                  39
8     C2  217525.340   286589.708                  39
9     C3  220210.084   362501.516                  52
10    D1  201416.876   252427.012                  26
11    D2  208128.736   248399.896                  13

## 📊 5. Calcul des bornes ANSTAT par Barème × Grade

On calcule le **min** et **max** de `Montant brut sans indemnités` pour chaque combinaison SECTEUR (= Barème) × GRADE.

In [7]:
# Min/Max par SECTEUR + GRADE
df_bornes_bareme_grade = (
    df_anstat
    .groupby(["SECTEUR", "GRADE"])
    .agg(
        ANSTAT_min=("Montant brut sans indemnités", "min"),
        ANSTAT_max=("Montant brut sans indemnités", "max"),
        ANSTAT_nb_echelons=("Montant brut sans indemnités", "count")
    )
    .reset_index()
    .sort_values(["SECTEUR", "GRADE"])
)

print("📋 Bornes ANSTAT par SECTEUR × GRADE (Montant brut sans indemnités) :")
print("=" * 80)
df_bornes_bareme_grade

📋 Bornes ANSTAT par SECTEUR × GRADE (Montant brut sans indemnités) :
================================================================================

           SECTEUR GRADE  ANSTAT_min  ANSTAT_max  ANSTAT_nb_echelons
0   Barême Général    A3  312833.752  570569.176                  13
1   Barême Général    A4  340284.588  662453.868                  13
2   Barême Général    A5  379077.796  687823.356                  13
3   Barême Général    A6  473043.836  695877.588                  13
4   Barême Général    A7  646209.824  750914.840                   8
..             ...   ...         ...         ...                 ...
60  para militaire    A7  666209.824  770914.840                   8
61  para militaire    B3  292562.592  465728.580                  13
62  para militaire    C1  223498.224  271823.616                  13
63  para militaire    C2  227525.340  286589.708                  13
64  para militaire    C3  230210.084  316121.892                  13

[65 rows x 5 columns]

## 📂 6. Chargement des indicateurs — Feuilles GRADE

On charge toutes les feuilles `GRADE_*` du fichier indicateurs.

In [8]:
xls = pd.ExcelFile(PATH_INDICATEURS)

# Identifier les feuilles GRADE
grade_sheets = [s for s in xls.sheet_names if s.startswith('GRADE_')]
print(f"📋 Feuilles GRADE trouvées : {grade_sheets}")

# Charger et concaténer toutes les feuilles GRADE
dfs_grade = []
for sheet in grade_sheets:
    df = pd.read_excel(xls, sheet_name=sheet, header=None)
    # Les vraies données commencent à la ligne 4 (index 4), header à la ligne 3
    header_row = df.iloc[3].tolist()
    df_data = df.iloc[4:].copy()
    df_data.columns = header_row
    df_data = df_data.reset_index(drop=True)
    # Convertir les colonnes numériques
    for col in ['ANNEE', 'MOIS_NUM', 'Effectif', 'Revenu_moyen', 'Revenu_median',
                'Revenu_min', 'Revenu_max', 'Revenu_p25', 'Revenu_p75']:
        if col in df_data.columns:
            df_data[col] = pd.to_numeric(df_data[col], errors='coerce')
    dfs_grade.append(df_data)

df_indicateurs_grade = pd.concat(dfs_grade, ignore_index=True)
print(f"\n✅ {len(df_indicateurs_grade)} lignes chargées")
print(f"Années : {sorted(df_indicateurs_grade['ANNEE'].unique())}")
print(f"Grades : {sorted(df_indicateurs_grade['GRADE_PRINCIPAL'].unique())}")
df_indicateurs_grade.head()

📋 Feuilles GRADE trouvées : ['GRADE_A3', 'GRADE_A4', 'GRADE_A5', 'GRADE_A6', 'GRADE_A7', 'GRADE_B1', 'GRADE_B3', 'GRADE_C1', 'GRADE_C2', 'GRADE_C3', 'GRADE_D1', 'GRADE_D2']

✅ 288 lignes chargées
Années : [np.int64(2024), np.int64(2025)]
Grades : ['A3', 'A4', 'A5', 'A6', 'A7', 'B1', 'B3', 'C1', 'C2', 'C3', 'D1', 'D2']

,ANNEE,MOIS_NUM,MOIS,GRADE_PRINCIPAL,Effectif,Revenu_moyen,Revenu_median,Revenu_min,Revenu_max,Revenu_p25,Revenu_p75
0,2024,1,Janvier,A3,39166,481451,456838,297834,796187,413883,555015
1,2024,2,Février,A3,40121,489845,463632,297836,798031,416936,564967
2,2024,3,Mars,A3,41029,485310,459338,297836,798106,413883,560570
3,2024,4,Avril,A3,41545,482362,457995,297834,796187,412822,556222
4,2024,5,Mai,A3,41940,480086,456838,297836,796187,408883,553304

## 📂 7. Chargement des indicateurs — Feuilles BAREME × GRADE

On charge les feuilles `BAREME_G_*` qui donnent les indicateurs par Barème × Grade.

In [9]:
# Identifier les feuilles BAREME_G (Barème × Grade)
bareme_g_sheets = [s for s in xls.sheet_names if s.startswith('BAREME_G_')]
print(f"📋 Feuilles BAREME_G trouvées : {bareme_g_sheets}")

# Charger et concaténer
dfs_bareme_g = []
for sheet in bareme_g_sheets:
    df = pd.read_excel(xls, sheet_name=sheet, header=None)
    header_row = df.iloc[3].tolist()
    df_data = df.iloc[4:].copy()
    df_data.columns = header_row
    df_data = df_data.reset_index(drop=True)
    for col in ['ANNEE', 'MOIS_NUM', 'Effectif', 'Revenu_moyen', 'Revenu_median',
                'Revenu_min', 'Revenu_max', 'Revenu_p25', 'Revenu_p75']:
        if col in df_data.columns:
            df_data[col] = pd.to_numeric(df_data[col], errors='coerce')
    dfs_bareme_g.append(df_data)

df_indicateurs_bareme_g = pd.concat(dfs_bareme_g, ignore_index=True)
print(f"\n✅ {len(df_indicateurs_bareme_g)} lignes chargées")
print(f"Barèmes : {sorted(df_indicateurs_bareme_g['bareme'].unique())}")
print(f"Grades  : {sorted(df_indicateurs_bareme_g['GRADE_PRINCIPAL'].unique())}")
df_indicateurs_bareme_g.head()

📋 Feuilles BAREME_G trouvées : ['BAREME_G_Bar_me_G_n_ral', 'BAREME_G_CORPS_DIPL', 'BAREME_G_CORPS_PREF', 'BAREME_G_Cadre_Sup_Sant_', 'BAREME_G_ENS_SEC___PRIM', 'BAREME_G_ENS_SUP', 'BAREME_G_GREFFE', 'BAREME_G_Informaticien', 'BAREME_G_MAGISTRAT_', 'BAREME_G_SECRETAIRE_DIRECTION', 'BAREME_G_Tech_Sant_']

✅ 1311 lignes chargées
Barèmes : ['Barême Général', 'CORPS DIPL', 'CORPS PREF', 'Cadre-Sup-Santé', 'ENS SEC & PRIM', 'ENS SUP', 'GREFFE', 'Informaticien', 'MAGISTRAT ', 'SECRETAIRE DIRECTION', 'Tech-Santé']
Grades  : ['A3', 'A4', 'A5', 'A6', 'A7', 'B1', 'B3', 'C1', 'C2', 'C3', 'D1', 'D2']

,ANNEE,MOIS_NUM,MOIS,bareme,GRADE_PRINCIPAL,Effectif,Revenu_moyen,Revenu_median,Revenu_min,Revenu_max,Revenu_p25,Revenu_p75
0,2024,1,Janvier,Barême Général,A3,8996,383856,382822,297834,598304,325655,424436
1,2024,1,Janvier,Barême Général,A4,4280,461710,450544,325286,692502,373474,528403
2,2024,1,Janvier,Barême Général,A5,1612,615301,621444,382502,720324,575324,670142
3,2024,1,Janvier,Barême Général,A6,433,663894,673379,452677,728379,651581,685879
4,2024,1,Janvier,Barême Général,A7,198,697936,695411,620090,768416,680092,715411

## ✅ 8. Vérification par GRADE

Pour chaque mois, on vérifie si :
- `Revenu_min` des indicateurs ≥ `ANSTAT_min` (le min observé ne peut pas être en dessous de la grille)
- `Revenu_max` des indicateurs ≤ `ANSTAT_max` (le max observé ne peut pas dépasser la grille)

Un salaire **hors** de ces bornes indique un agent dont le salaire ne correspond pas au barème ANSTAT.

In [10]:
# Fusionner indicateurs GRADE avec bornes ANSTAT
df_verif_grade = df_indicateurs_grade.merge(
    df_bornes_grade,
    left_on="GRADE_PRINCIPAL",
    right_on="GRADE",
    how="left"
)

# Vérifications
df_verif_grade["min_OK"] = df_verif_grade["Revenu_min"] >= df_verif_grade["ANSTAT_min"]
df_verif_grade["max_OK"] = df_verif_grade["Revenu_max"] <= df_verif_grade["ANSTAT_max"]
df_verif_grade["ecart_min"] = df_verif_grade["Revenu_min"] - df_verif_grade["ANSTAT_min"]
df_verif_grade["ecart_max"] = df_verif_grade["Revenu_max"] - df_verif_grade["ANSTAT_max"]

# Résumé
nb_total = len(df_verif_grade)
nb_min_ok = df_verif_grade["min_OK"].sum()
nb_max_ok = df_verif_grade["max_OK"].sum()

print("=" * 70)
print("         RÉSULTAT DE VÉRIFICATION PAR GRADE")
print("=" * 70)
print(f"Total lignes vérifiées : {nb_total}")
print(f"Min OK (Revenu_min ≥ ANSTAT_min) : {nb_min_ok}/{nb_total} ({100*nb_min_ok/nb_total:.1f}%)")
print(f"Max OK (Revenu_max ≤ ANSTAT_max) : {nb_max_ok}/{nb_total} ({100*nb_max_ok/nb_total:.1f}%)")
print("=" * 70)

======================================================================
         RÉSULTAT DE VÉRIFICATION PAR GRADE
======================================================================
Total lignes vérifiées : 288
Min OK (Revenu_min ≥ ANSTAT_min) : 50/288 (17.4%)
Max OK (Revenu_max ≤ ANSTAT_max) : 40/288 (13.9%)
======================================================================

### ⚠️ Détail des anomalies MIN par Grade

In [11]:
# Lignes où le min observé est inférieur à la borne ANSTAT
anomalies_min_grade = df_verif_grade[~df_verif_grade["min_OK"]].copy()

if len(anomalies_min_grade) > 0:
    print(f"⚠️  {len(anomalies_min_grade)} mois×grade où Revenu_min < ANSTAT_min :")
    display_cols = ["ANNEE", "MOIS", "GRADE_PRINCIPAL", "Effectif",
                    "Revenu_min", "ANSTAT_min", "ecart_min"]
    print(anomalies_min_grade[display_cols].to_string(index=False))
else:
    print("✅ Aucune anomalie MIN par Grade : tous les Revenu_min ≥ ANSTAT_min")

⚠️  238 mois×grade où Revenu_min < ANSTAT_min :
 ANNEE      MOIS GRADE_PRINCIPAL  Effectif  Revenu_min  ANSTAT_min  ecart_min
  2024   Janvier              A3     39166      297834  312833.752 -14999.752
  2024   Février              A3     40121      297836  312833.752 -14997.752
  2024      Mars              A3     41029      297836  312833.752 -14997.752
  2024     Avril              A3     41545      297834  312833.752 -14999.752
  2024       Mai              A3     41940      297836  312833.752 -14997.752
  2024      Juin              A3     42099      297836  312833.752 -14997.752
  2024   Juillet              A3     43463      297836  312833.752 -14997.752
  2024      Août              A3     44060      297836  312833.752 -14997.752
  2024 Septembre              A3     44346      297834  312833.752 -14999.752
  2024   Octobre              A3     44791      297836  312833.752 -14997.752
  2024  Novembre              A3     45224      297836  312833.752 -14997.752
  2024  Décembre              A3     45207      297836  312833.752 -14997.752
  2025   Janvier              A3     44258      297836  312833.752 -14997.752
  2025   Février              A3     44558      297836  312833.752 -14997.752
  2025      Mars              A3     45358      297836  312833.752 -14997.752
  2025     Avril              A3     44546      297836  312833.752 -14997.752
  2025       Mai              A3     46494      297836  312833.752 -14997.752
  2025      Juin              A3     46834      297836  312833.752 -14997.752
  2025   Juillet              A3     47338      297836  312833.752 -14997.752
  2025      Août              A3     48088      297836  312833.752 -14997.752
  2025 Septembre              A3     48343      297836  312833.752 -14997.752
  2025   Octobre              A3     48538      297836  312833.752 -14997.752
  2025  Novembre              A3     48662      297836  312833.752 -14997.752
  2025  Décembre              A3     48723      297834  312833.752 -14999.752
  2024   Janvier              A4     29746      325286  340284.588 -14998.588
  2024   Février              A4     30274      325286  340284.588 -14998.588
  2024      Mars              A4     30755      325286  340284.588 -14998.588
  2024     Avril              A4     31152      325286  340284.588 -14998.588
  2024       Mai              A4     31087      325286  340284.588 -14998.588
  2024      Juin              A4     31230      325286  340284.588 -14998.588
  2024   Juillet              A4     31994      325286  340284.588 -14998.588
  2024      Août              A4     32494      325286  340284.588 -14998.588
  2024 Septembre              A4     32784      325286  340284.588 -14998.588
  2024   Octobre              A4     33035      325286  340284.588 -14998.588
  2024  Novembre              A4     33088      325286  340284.588 -14998.588
  2024  Décembre              A4     33119      325286  340284.588 -14998.588
  2025   Janvier              A4     32968      325286  340284.588 -14998.588
  2025   Février              A4     33349      325286  340284.588 -14998.588
  2025      Mars              A4     34033      325286  340284.588 -14998.588
  2025     Avril              A4     33325      325286  340284.588 -14998.588
  2025       Mai              A4     34569      325286  340284.588 -14998.588
  2025      Juin              A4     34887      325286  340284.588 -14998.588
  2025   Juillet              A4     35095      325286  340284.588 -14998.588
  2025      Août              A4     35334      325286  340284.588 -14998.588
  2025 Septembre              A4     35513      325286  340284.588 -14998.588
  2025   Octobre              A4     35586      325286  340284.588 -14998.588
  2025  Novembre              A4     35569      325286  340284.588 -14998.588
  2025  Décembre              A4     35682      325286  340284.588 -14998.588
  2024   Janvier              A6      2270      452677  473043.836 -20366.836
  2024   Février              A6      2270      452677  473043.836 -20366.836
  2024      Mars              A6      2196      452677  473043.836 -20366.836
  2024     Avril              A6      2206      452677  473043.836 -20366.836
  2024       Mai              A6      2198      452677  473043.836 -20366.836
  2024      Juin              A6      2180      452677  473043.836 -20366.836
  2024   Juillet              A6      2400      452677  473043.836 -20366.836
  2024      Août              A6      2415      452677  473043.836 -20366.836
  2024 Septembre              A6      2414      452677  473043.836 -20366.836
  2024  Novembre              A6      2522      450544  473043.836 -22499.836
  2024  Décembre              A6      2523      450544  473043.836 -22499.836
  2025   Février              A6      2610      450544  473043.836 -22499.836
  2025      Mars              A6      2553      450544  473043.836 -22499.836
  2025     Avril              A6      2607      450544  473043.836 -22499.836
  2025       Mai              A6      3002      450544  473043.836 -22499.836
  2025      Juin              A6      3053      450544  473043.836 -22499.836
  2025   Juillet              A6      3119      450544  473043.836 -22499.836
  2025      Août              A6      3233      450544  473043.836 -22499.836
  2025 Septembre              A6      3264      465544  473043.836  -7499.836
  2025   Octobre              A6      3309      465544  473043.836  -7499.836
  2025  Novembre              A6      3350      465544  473043.836  -7499.836
  2025  Décembre              A6      3427      465544  473043.836  -7499.836
  2024   Janvier              A7      1822      616213  646209.824 -29996.824
  2024   Février              A7      1889      620090  646209.824 -26119.824
  2024      Mars              A7      1987      620090  646209.824 -26119.824
  2024     Avril              A7      1857      620090  646209.824 -26119.824
  2024       Mai              A7      1875      620090  646209.824 -26119.824
  2024      Juin              A7      1919      620090  646209.824 -26119.824
  2024   Juillet              A7      1959      620090  646209.824 -26119.824
  2024      Août              A7      1968      630977  646209.824 -15232.824
  2024 Septembre              A7      1979      630977  646209.824 -15232.824
  2024   Octobre              A7      2019      623713  646209.824 -22496.824
  2024  Novembre              A7      2036      623713  646209.824 -22496.824
  2024  Décembre              A7      2040      623713  646209.824 -22496.824
  2025   Janvier              A7      1848      630977  646209.824 -15232.824
  2025   Février              A7      1991      623713  646209.824 -22496.824
  2025      Mars              A7      1941      623713  646209.824 -22496.824
  2025     Avril              A7      2005      623713  646209.824 -22496.824
  2025       Mai              A7      2138      623713  646209.824 -22496.824
  2025      Juin              A7      2150      623713  646209.824 -22496.824
  2025   Juillet              A7      2183      623713  646209.824 -22496.824
  2025      Août              A7      2204      623713  646209.824 -22496.824
  2025 Septembre              A7      2241      616213  646209.824 -29996.824
  2025   Octobre              A7      2242      616213  646209.824 -29996.824
  2025  Novembre              A7      2304      616213  646209.824 -29996.824
  2025  Décembre              A7      2302      616213  646209.824 -29996.824
  2024   Janvier              B1      2500      229743  241688.036 -11945.036
  2024   Février              B1      2581      229743  241688.036 -11945.036
  2024      Mars              B1      2727      229743  241688.036 -11945.036
  2024     Avril              B1      2770      229743  241688.036 -11945.036
  2024       Mai              B1      2807      229743  241688.036 -11945.036
  2024      Juin              B1      2874      229743  241688.036 -11945.036
  2024   Juillet              B1      2931      229743  241688.036 -11945.036
  2024      Août              B1      2984      229743  241688.036 -11945.036
  2024 Septembre              B1      3077      229743  241688.036 -11945.036
  2024   Octobre              B1      3094      229743  241688.036 -11945.036
  2024  Novembre              B1      3095      229743  241688.036 -11945.036
  2024  Décembre              B1      3103      229743  241688.036 -11945.036
  2025   Janvier              B1      3125      229743  241688.036 -11945.036
  2025   Février              B1      3257      229743  241688.036 -11945.036
  2025      Mars              B1      3347      229743  241688.036 -11945.036
  2025     Avril              B1      3257      229743  241688.036 -11945.036
  2025       Mai              B1      3491      229743  241688.036 -11945.036
  2025      Juin              B1      3617      229743  241688.036 -11945.036
  2025   Juillet              B1      3645      229743  241688.036 -11945.036
  2025      Août              B1      3686      229743  241688.036 -11945.036
  2025 Septembre              B1      3698      229743  241688.036 -11945.036
  2025   Octobre              B1      3716      229743  241688.036 -11945.036
  2025  Novembre              B1      3749      229743  241688.036 -11945.036
  2025  Décembre              B1      3764      229743  241688.036 -11945.036
  2024   Janvier              B3    103233      260063  272562.592 -12499.592
  2024   Février              B3    103199      260064  272562.592 -12498.592
  2024      Mars              B3    103867      260064  272562.592 -12498.592
  2024     Avril              B3    104577      260063  272562.592 -12499.592
  2024       Mai              B3    104316      260063  272562.592 -12499.592
  2024      Juin              B3    104565      259793  272562.592 -12769.592
  2024   Juillet              B3    104739      259793  272562.592 -12769.592
  2024      Août              B3    105463      259793  272562.592 -12769.592
  2024 Septembre              B3    105994      259793  272562.592 -12769.592
  2024   Octobre              B3    105730      259793  272562.592 -12769.592
  2024  Novembre              B3    105318      259793  272562.592 -12769.592
  2024  Décembre              B3    105331      259793  272562.592 -12769.592
  2025   Janvier              B3    103582      259793  272562.592 -12769.592
  2025   Février              B3    105233      259793  272562.592 -12769.592
  2025      Mars              B3    107037      259793  272562.592 -12769.592
  2025     Avril              B3    105207      259793  272562.592 -12769.592
  2025       Mai              B3    106763      259793  272562.592 -12769.592
  2025      Juin              B3    109761      259793  272562.592 -12769.592
  2025   Juillet              B3    109692      259793  272562.592 -12769.592
  2025      Août              B3    109009      259793  272562.592 -12769.592
  2025 Septembre              B3    108731      260063  272562.592 -12499.592
  2025   Octobre              B3    108778      260063  272562.592 -12499.592
  2025  Novembre              B3    108900      260063  272562.592 -12499.592
  2025  Décembre              B3    108510      260063  272562.592 -12499.592
  2024   Janvier              C1     11552      203500  213498.224  -9998.224
  2024   Février              C1     11590      202830  213498.224 -10668.224
  2024      Mars              C1     11863      202944  213498.224 -10554.224
  2024     Avril              C1     11922      203500  213498.224  -9998.224
  2024       Mai              C1     11908      202885  213498.224 -10613.224
  2024      Juin              C1     11995      202830  213498.224 -10668.224
  2024   Juillet              C1     12062      203065  213498.224 -10433.224
  2024      Août              C1     12085      202830  213498.224 -10668.224
  2024 Septembre              C1     12184      203500  213498.224  -9998.224
  2024   Octobre              C1     12286      203500  213498.224  -9998.224
  2024  Novembre              C1     12296      203498  213498.224 -10000.224
  2024  Décembre              C1     12329      203498  213498.224 -10000.224
  2025   Janvier              C1     12285      203004  213498.224 -10494.224
  2025   Février              C1     12557      202916  213498.224 -10582.224
  2025      Mars              C1     12647      203006  213498.224 -10492.224
  2025     Avril              C1     12556      202916  213498.224 -10582.224
  2025       Mai              C1     12356      202975  213498.224 -10523.224
  2025      Juin              C1     12297      203090  213498.224 -10408.224
  2025   Juillet              C1     12292      202885  213498.224 -10613.224
  2025      Août              C1     12333      203090  213498.224 -10408.224
  2025 Septembre              C1     12401      203498  213498.224 -10000.224
  2025   Octobre              C1     12421      203498  213498.224 -10000.224
  2025  Novembre              C1     12450      203498  213498.224 -10000.224
  2025  Décembre              C1     12457      203498  213498.224 -10000.224
  2024   Janvier              C2      4643      207526  217525.340  -9999.340
  2024   Février              C2      4640      206856  217525.340 -10669.340
  2024      Mars              C2      4639      207526  217525.340  -9999.340
  2024     Avril              C2      4631      207202  217525.340 -10323.340
  2024       Mai              C2      4614      207526  217525.340  -9999.340
  2024      Juin              C2      4617      207526  217525.340  -9999.340
  2024   Juillet              C2      4644      207526  217525.340  -9999.340
  2024      Août              C2      4608      206942  217525.340 -10583.340
  2024 Septembre              C2      4644      207526  217525.340  -9999.340
  2024   Octobre              C2      4695      207526  217525.340  -9999.340
  2024  Novembre              C2      4696      207526  217525.340  -9999.340
  2024  Décembre              C2      4693      207526  217525.340  -9999.340
  2025   Janvier              C2      4563      207526  217525.340  -9999.340
  2025   Février              C2      4581      207526  217525.340  -9999.340
  2025      Mars              C2      4620      207526  217525.340  -9999.340
  2025     Avril              C2      4576      207526  217525.340  -9999.340
  2025       Mai              C2      4629      207526  217525.340  -9999.340
  2025      Juin              C2      4613      207526  217525.340  -9999.340
  2025   Juillet              C2      4596      207526  217525.340  -9999.340
  2025      Août              C2      4596      207526  217525.340  -9999.340
  2025 Septembre              C2      4599      207526  217525.340  -9999.340
  2025   Octobre              C2      4581      207526  217525.340  -9999.340
  2025  Novembre              C2      4557      207526  217525.340  -9999.340
  2025  Décembre              C2      4542      207526  217525.340  -9999.340
  2024   Janvier              C3     37697      210212  220210.084  -9998.084
  2024   Février              C3     37640      210212  220210.084  -9998.084
  2024      Mars              C3     37805      210212  220210.084  -9998.084
  2024     Avril              C3     37652      210212  220210.084  -9998.084
  2024       Mai              C3     37429      210212  220210.084  -9998.084
  2024      Juin              C3     37417      210212  220210.084  -9998.084
  2024   Juillet              C3     37357      210212  220210.084  -9998.084
  2024      Août              C3     37308      210212  220210.084  -9998.084
  2024 Septembre              C3     37725      210212  220210.084  -9998.084
  2024   Octobre              C3     40128      210212  220210.084  -9998.084
  2024  Novembre              C3     42231      210212  220210.084  -9998.084
  2024  Décembre              C3     42370      210212  220210.084  -9998.084
  2025   Janvier              C3     42634      210212  220210.084  -9998.084
  2025   Février              C3     42571      210212  220210.084  -9998.084
  2025      Mars              C3     42766      210212  220210.084  -9998.084
  2025     Avril              C3     42565      210212  220210.084  -9998.084
  2025       Mai              C3     44888      211922  220210.084  -8288.084
  2025      Juin              C3     43999      211922  220210.084  -8288.084
  2025   Juillet              C3     44228      211922  220210.084  -8288.084
  2025      Août              C3     44494      211922  220210.084  -8288.084
  2025 Septembre              C3     44803      210210  220210.084 -10000.084
  2025   Octobre              C3     48093      210210  220210.084 -10000.084
  2025  Novembre              C3     48398      210210  220210.084 -10000.084
  2025  Décembre              C3     48534      210210  220210.084 -10000.084
  2024   Janvier              D1      5125      191417  201416.876  -9999.876
  2024   Février              D1      5152      191417  201416.876  -9999.876
  2024      Mars              D1      5288      191417  201416.876  -9999.876
  2024     Avril              D1      5477      191417  201416.876  -9999.876
  2024       Mai              D1      5484      191417  201416.876  -9999.876
  2024      Juin              D1      5496      191418  201416.876  -9998.876
  2024   Juillet              D1      5502      191418  201416.876  -9998.876
  2024      Août              D1      5552      191418  201416.876  -9998.876
  2024 Septembre              D1      5670      191418  201416.876  -9998.876
  2024   Octobre              D1      5638      191418  201416.876  -9998.876
  2024  Novembre              D1      5624      191418  201416.876  -9998.876
  2024  Décembre              D1      5638      191418  201416.876  -9998.876
  2025   Janvier              D1      5539      191418  201416.876  -9998.876
  2025   Février              D1      5640      191418  201416.876  -9998.876
  2025      Mars              D1      5693      191418  201416.876  -9998.876
  2025     Avril              D1      5640      191418  201416.876  -9998.876
  2025       Mai              D1      5788      191418  201416.876  -9998.876
  2025      Juin              D1      5808      191418  201416.876  -9998.876
  2025   Juillet              D1      5830      191418  201416.876  -9998.876
  2025      Août              D1      5834      191418  201416.876  -9998.876
  2025 Septembre              D1      5882      191418  201416.876  -9998.876
  2025   Octobre              D1      5911      191418  201416.876  -9998.876
  2025  Novembre              D1      5918      191418  201416.876  -9998.876
  2025  Décembre              D1      5893      191418  201416.876  -9998.876

### ⚠️ Détail des anomalies MAX par Grade

In [12]:
# Lignes où le max observé dépasse la borne ANSTAT
anomalies_max_grade = df_verif_grade[~df_verif_grade["max_OK"]].copy()

if len(anomalies_max_grade) > 0:
    print(f"⚠️  {len(anomalies_max_grade)} mois×grade où Revenu_max > ANSTAT_max :")
    display_cols = ["ANNEE", "MOIS", "GRADE_PRINCIPAL", "Effectif",
                    "Revenu_max", "ANSTAT_max", "ecart_max"]
    print(anomalies_max_grade[display_cols].to_string(index=False))
else:
    print("✅ Aucune anomalie MAX par Grade : tous les Revenu_max ≤ ANSTAT_max")

⚠️  248 mois×grade où Revenu_max > ANSTAT_max :
 ANNEE      MOIS GRADE_PRINCIPAL  Effectif  Revenu_max  ANSTAT_max  ecart_max
  2024   Janvier              A3     39166      796187  761186.000  35001.000
  2024   Février              A3     40121      798031  761186.000  36845.000
  2024      Mars              A3     41029      798106  761186.000  36920.000
  2024     Avril              A3     41545      796187  761186.000  35001.000
  2024       Mai              A3     41940      796187  761186.000  35001.000
  2024      Juin              A3     42099      799008  761186.000  37822.000
  2024   Juillet              A3     43463      797766  761186.000  36580.000
  2024      Août              A3     44060      797766  761186.000  36580.000
  2024 Septembre              A3     44346      797766  761186.000  36580.000
  2024   Octobre              A3     44791      796187  761186.000  35001.000
  2024  Novembre              A3     45224      797766  761186.000  36580.000
  2024  Décembre              A3     45207      796187  761186.000  35001.000
  2025   Janvier              A3     44258      797766  761186.000  36580.000
  2025   Février              A3     44558      798872  761186.000  37686.000
  2025      Mars              A3     45358      796187  761186.000  35001.000
  2025     Avril              A3     44546      798872  761186.000  37686.000
  2025       Mai              A3     46494      798313  761186.000  37127.000
  2025      Juin              A3     46834      796187  761186.000  35001.000
  2025   Juillet              A3     47338      798791  761186.000  37605.000
  2025      Août              A3     48088      798308  761186.000  37122.000
  2025 Septembre              A3     48343      797748  761186.000  36562.000
  2025   Octobre              A3     48538      797766  761186.000  36580.000
  2025  Novembre              A3     48662      797766  761186.000  36580.000
  2025  Décembre              A3     48723      796187  761186.000  35001.000
  2024   Janvier              A4     29746     1068184 1051606.168  16577.832
  2024   Février              A4     30274     1090651 1051606.168  39044.832
  2024      Mars              A4     30755     1099983 1051606.168  48376.832
  2024     Avril              A4     31152     1074108 1051606.168  22501.832
  2024       Mai              A4     31087     1074108 1051606.168  22501.832
  2024      Juin              A4     31230     1080320 1051606.168  28713.832
  2024   Juillet              A4     31994     1074108 1051606.168  22501.832
  2024      Août              A4     32494     1100803 1051606.168  49196.832
  2024 Septembre              A4     32784     1074108 1051606.168  22501.832
  2024   Octobre              A4     33035     1076888 1051606.168  25281.832
  2024  Novembre              A4     33088     1074108 1051606.168  22501.832
  2024  Décembre              A4     33119     1074108 1051606.168  22501.832
  2025   Janvier              A4     32968     1074108 1051606.168  22501.832
  2025   Février              A4     33349     1082572 1051606.168  30965.832
  2025      Mars              A4     34033     1088321 1051606.168  36714.832
  2025     Avril              A4     33325     1082572 1051606.168  30965.832
  2025       Mai              A4     34569     1081608 1051606.168  30001.832
  2025      Juin              A4     34887     1081608 1051606.168  30001.832
  2025   Juillet              A4     35095     1081608 1051606.168  30001.832
  2025      Août              A4     35334     1083146 1051606.168  31539.832
  2025 Septembre              A4     35513     1098725 1051606.168  47118.832
  2025   Octobre              A4     35586     1075645 1051606.168  24038.832
  2025  Novembre              A4     35569     1074108 1051606.168  22501.832
  2025  Décembre              A4     35682     1074108 1051606.168  22501.832
  2024   Janvier              A5     15938     1144330 1109328.164  35001.836
  2024   Février              A5     16062     1144279 1109328.164  34950.836
  2024      Mars              A5     16179     1144330 1109328.164  35001.836
  2024     Avril              A5     16381     1144330 1109328.164  35001.836
  2024       Mai              A5     16329     1144330 1109328.164  35001.836
  2024      Juin              A5     16427     1144330 1109328.164  35001.836
  2024   Juillet              A5     16608     1144330 1109328.164  35001.836
  2024      Août              A5     16648     1161483 1109328.164  52154.836
  2024 Septembre              A5     16740     1144330 1109328.164  35001.836
  2024   Octobre              A5     16775     1144330 1109328.164  35001.836
  2024  Novembre              A5     16798     1144330 1109328.164  35001.836
  2024  Décembre              A5     16818     1144330 1109328.164  35001.836
  2025   Janvier              A5     16216     1144330 1109328.164  35001.836
  2025   Février              A5     16098     1162297 1109328.164  52968.836
  2025      Mars              A5     16020     1144330 1109328.164  35001.836
  2025     Avril              A5     15788     1162297 1109328.164  52968.836
  2025       Mai              A5     15651     1161732 1109328.164  52403.836
  2025      Juin              A5     16114     1144330 1109328.164  35001.836
  2025   Juillet              A5     16137     1144330 1109328.164  35001.836
  2025      Août              A5     16185     1144330 1109328.164  35001.836
  2025 Septembre              A5     16235     1144330 1109328.164  35001.836
  2025   Octobre              A5     16176     1144330 1109328.164  35001.836
  2025  Novembre              A5     16205     1144330 1109328.164  35001.836
  2025  Décembre              A5     16237     1144330 1109328.164  35001.836
  2024   Janvier              A6      2270     1362670 1357666.984   5003.016
  2024   Février              A6      2270     1362670 1357666.984   5003.016
  2024      Mars              A6      2196     1362669 1357666.984   5002.016
  2024     Avril              A6      2206     1362670 1357666.984   5003.016
  2024       Mai              A6      2198     1362670 1357666.984   5003.016
  2024      Juin              A6      2180     1362670 1357666.984   5003.016
  2024   Juillet              A6      2400     1394777 1357666.984  37110.016
  2024      Août              A6      2415     1424543 1357666.984  66876.016
  2024 Septembre              A6      2414     1362670 1357666.984   5003.016
  2024   Octobre              A6      2460     1362670 1357666.984   5003.016
  2024  Novembre              A6      2522     1362670 1357666.984   5003.016
  2024  Décembre              A6      2523     1362670 1357666.984   5003.016
  2025   Janvier              A6      2440     1362670 1357666.984   5003.016
  2025   Février              A6      2610     1415417 1357666.984  57750.016
  2025      Mars              A6      2553     1380169 1357666.984  22502.016
  2025     Avril              A6      2607     1415417 1357666.984  57750.016
  2025       Mai              A6      3002     1380169 1357666.984  22502.016
  2025      Juin              A6      3053     1387035 1357666.984  29368.016
  2025   Juillet              A6      3119     1380169 1357666.984  22502.016
  2025      Août              A6      3233     1380169 1357666.984  22502.016
  2025 Septembre              A6      3264     1380169 1357666.984  22502.016
  2025   Octobre              A6      3309     1423599 1357666.984  65932.016
  2025  Novembre              A6      3350     1412920 1357666.984  55253.016
  2025  Décembre              A6      3427     1380169 1357666.984  22502.016
  2024      Août              A7      1968     1514138 1461236.680  52901.320
  2024   Octobre              A7      2019     1476407 1461236.680  15170.320
  2025   Février              A7      1991     1528451 1461236.680  67214.320
  2025      Mars              A7      1941     1508539 1461236.680  47302.320
  2025     Avril              A7      2005     1528451 1461236.680  67214.320
  2025   Juillet              A7      2183     1523585 1461236.680  62348.320
  2025      Août              A7      2204     1529212 1461236.680  67975.320
  2025  Novembre              A7      2304     1506425 1461236.680  45188.320
  2024   Janvier              B1      2500      353758  338338.820  15419.180
  2024   Février              B1      2581      353758  338338.820  15419.180
  2024      Mars              B1      2727      353758  338338.820  15419.180
  2024     Avril              B1      2770      353938  338338.820  15599.180
  2024       Mai              B1      2807      352343  338338.820  14004.180
  2024      Juin              B1      2874      354944  338338.820  16605.180
  2024   Juillet              B1      2931      351628  338338.820  13289.180
  2024      Août              B1      2984      353643  338338.820  15304.180
  2024 Septembre              B1      3077      351628  338338.820  13289.180
  2024   Octobre              B1      3094      348389  338338.820  10050.180
  2024  Novembre              B1      3095      348758  338338.820  10419.180
  2024  Décembre              B1      3103      348758  338338.820  10419.180
  2025   Janvier              B1      3125      354128  338338.820  15789.180
  2025   Février              B1      3257      354128  338338.820  15789.180
  2025      Mars              B1      3347      354128  338338.820  15789.180
  2025     Avril              B1      3257      354128  338338.820  15789.180
  2025       Mai              B1      3491      354128  338338.820  15789.180
  2025      Juin              B1      3617      354128  338338.820  15789.180
  2025   Juillet              B1      3645      354128  338338.820  15789.180
  2025      Août              B1      3686      354128  338338.820  15789.180
  2025 Septembre              B1      3698      354128  338338.820  15789.180
  2025   Octobre              B1      3716      350839  338338.820  12500.180
  2025  Novembre              B1      3749      350839  338338.820  12500.180
  2025  Décembre              B1      3764      350839  338338.820  12500.180
  2024   Janvier              B3    103233      584648  557145.456  27502.544
  2024   Février              B3    103199      584961  557145.456  27815.544
  2024      Mars              B3    103867      584648  557145.456  27502.544
  2024     Avril              B3    104577      584648  557145.456  27502.544
  2024       Mai              B3    104316      584779  557145.456  27633.544
  2024      Juin              B3    104565      584914  557145.456  27768.544
  2024   Juillet              B3    104739      584648  557145.456  27502.544
  2024      Août              B3    105463      584726  557145.456  27580.544
  2024 Septembre              B3    105994      584648  557145.456  27502.544
  2024   Octobre              B3    105730      584648  557145.456  27502.544
  2024  Novembre              B3    105318      584647  557145.456  27501.544
  2024  Décembre              B3    105331      584647  557145.456  27501.544
  2025   Janvier              B3    103582      584647  557145.456  27501.544
  2025   Février              B3    105233      584647  557145.456  27501.544
  2025      Mars              B3    107037      584647  557145.456  27501.544
  2025     Avril              B3    105207      584647  557145.456  27501.544
  2025       Mai              B3    106763      584893  557145.456  27747.544
  2025      Juin              B3    109761      584793  557145.456  27647.544
  2025   Juillet              B3    109692      584647  557145.456  27501.544
  2025      Août              B3    109009      584647  557145.456  27501.544
  2025 Septembre              B3    108731      584647  557145.456  27501.544
  2025   Octobre              B3    108778      584647  557145.456  27501.544
  2025  Novembre              B3    108900      584647  557145.456  27501.544
  2025  Décembre              B3    108510      584647  557145.456  27501.544
  2024   Janvier              C1     11552      287748  275247.336  12500.664
  2024   Février              C1     11590      288550  275247.336  13302.664
  2024      Mars              C1     11863      287748  275247.336  12500.664
  2024     Avril              C1     11922      287748  275247.336  12500.664
  2024       Mai              C1     11908      287748  275247.336  12500.664
  2024      Juin              C1     11995      287748  275247.336  12500.664
  2024   Juillet              C1     12062      287748  275247.336  12500.664
  2024      Août              C1     12085      288813  275247.336  13565.664
  2024 Septembre              C1     12184      288720  275247.336  13472.664
  2024   Octobre              C1     12286      288720  275247.336  13472.664
  2024  Novembre              C1     12296      288720  275247.336  13472.664
  2024  Décembre              C1     12329      288720  275247.336  13472.664
  2025   Janvier              C1     12285      288720  275247.336  13472.664
  2025   Février              C1     12557      288720  275247.336  13472.664
  2025      Mars              C1     12647      288720  275247.336  13472.664
  2025     Avril              C1     12556      288720  275247.336  13472.664
  2025       Mai              C1     12356      288720  275247.336  13472.664
  2025      Juin              C1     12297      288720  275247.336  13472.664
  2025   Juillet              C1     12292      288720  275247.336  13472.664
  2025      Août              C1     12333      287748  275247.336  12500.664
  2025 Septembre              C1     12401      287748  275247.336  12500.664
  2025   Octobre              C1     12421      287748  275247.336  12500.664
  2025  Novembre              C1     12450      287748  275247.336  12500.664
  2025  Décembre              C1     12457      287748  275247.336  12500.664
  2024   Janvier              C2      4643      290297  286589.708   3707.292
  2024   Février              C2      4640      290063  286589.708   3473.292
  2024      Mars              C2      4639      290297  286589.708   3707.292
  2024     Avril              C2      4631      290297  286589.708   3707.292
  2024       Mai              C2      4614      290297  286589.708   3707.292
  2024      Juin              C2      4617      290297  286589.708   3707.292
  2024   Juillet              C2      4644      290297  286589.708   3707.292
  2024      Août              C2      4608      290298  286589.708   3708.292
  2024 Septembre              C2      4644      290297  286589.708   3707.292
  2024   Octobre              C2      4695      290297  286589.708   3707.292
  2024  Novembre              C2      4696      290297  286589.708   3707.292
  2024  Décembre              C2      4693      290297  286589.708   3707.292
  2025   Janvier              C2      4563      290297  286589.708   3707.292
  2025   Février              C2      4581      290297  286589.708   3707.292
  2025      Mars              C2      4620      290297  286589.708   3707.292
  2025     Avril              C2      4576      290297  286589.708   3707.292
  2025       Mai              C2      4629      290297  286589.708   3707.292
  2025      Juin              C2      4613      290297  286589.708   3707.292
  2025   Juillet              C2      4596      290297  286589.708   3707.292
  2025      Août              C2      4596      290297  286589.708   3707.292
  2025 Septembre              C2      4599      290297  286589.708   3707.292
  2025   Octobre              C2      4581      290297  286589.708   3707.292
  2025  Novembre              C2      4557      290297  286589.708   3707.292
  2025  Décembre              C2      4542      290297  286589.708   3707.292
  2024   Janvier              C3     37697      380002  362501.516  17500.484
  2024   Février              C3     37640      380002  362501.516  17500.484
  2024      Mars              C3     37805      380002  362501.516  17500.484
  2024     Avril              C3     37652      380002  362501.516  17500.484
  2024       Mai              C3     37429      380002  362501.516  17500.484
  2024      Juin              C3     37417      380002  362501.516  17500.484
  2024   Juillet              C3     37357      380366  362501.516  17864.484
  2024      Août              C3     37308      380594  362501.516  18092.484
  2024 Septembre              C3     37725      380002  362501.516  17500.484
  2024   Octobre              C3     40128      380002  362501.516  17500.484
  2024  Novembre              C3     42231      380002  362501.516  17500.484
  2024  Décembre              C3     42370      380002  362501.516  17500.484
  2025   Janvier              C3     42634      380002  362501.516  17500.484
  2025   Février              C3     42571      380605  362501.516  18103.484
  2025      Mars              C3     42766      380002  362501.516  17500.484
  2025     Avril              C3     42565      380605  362501.516  18103.484
  2025       Mai              C3     44888      380002  362501.516  17500.484
  2025      Juin              C3     43999      380002  362501.516  17500.484
  2025   Juillet              C3     44228      380002  362501.516  17500.484
  2025      Août              C3     44494      380002  362501.516  17500.484
  2025 Septembre              C3     44803      380391  362501.516  17889.484
  2025   Octobre              C3     48093      380002  362501.516  17500.484
  2025  Novembre              C3     48398      380002  362501.516  17500.484
  2025  Décembre              C3     48534      380002  362501.516  17500.484
  2024   Janvier              D1      5125      258265  252427.012   5837.988
  2024   Février              D1      5152      258265  252427.012   5837.988
  2024      Mars              D1      5288      258265  252427.012   5837.988
  2024     Avril              D1      5477      258265  252427.012   5837.988
  2024       Mai              D1      5484      258266  252427.012   5838.988
  2024      Juin              D1      5496      258266  252427.012   5838.988
  2024   Juillet              D1      5502      258266  252427.012   5838.988
  2024      Août              D1      5552      263902  252427.012  11474.988
  2024 Septembre              D1      5670      258266  252427.012   5838.988
  2024   Octobre              D1      5638      258266  252427.012   5838.988
  2024  Novembre              D1      5624      258266  252427.012   5838.988
  2024  Décembre              D1      5638      258266  252427.012   5838.988
  2025   Janvier              D1      5539      258266  252427.012   5838.988
  2025   Février              D1      5640      258266  252427.012   5838.988
  2025      Mars              D1      5693      264419  252427.012  11991.988
  2025     Avril              D1      5640      258266  252427.012   5838.988
  2025       Mai              D1      5788      260950  252427.012   8522.988
  2025      Juin              D1      5808      260950  252427.012   8522.988
  2025   Juillet              D1      5830      260950  252427.012   8522.988
  2025      Août              D1      5834      260950  252427.012   8522.988
  2025 Septembre              D1      5882      260950  252427.012   8522.988
  2025   Octobre              D1      5911      260950  252427.012   8522.988
  2025  Novembre              D1      5918      260950  252427.012   8522.988
  2025  Décembre              D1      5893      260950  252427.012   8522.988

### 📊 Synthèse par Grade (vue agrégée)

In [13]:
# Tableau de synthèse : pour chaque grade, nombre de mois en anomalie
synthese_grade = (
    df_verif_grade
    .groupby("GRADE_PRINCIPAL")
    .agg(
        nb_mois=("ANNEE", "count"),
        nb_min_anomalies=("min_OK", lambda x: (~x).sum()),
        nb_max_anomalies=("max_OK", lambda x: (~x).sum()),
        ecart_min_moyen=("ecart_min", lambda x: x[x < 0].mean() if (x < 0).any() else 0),
        ecart_max_moyen=("ecart_max", lambda x: x[x > 0].mean() if (x > 0).any() else 0),
        Revenu_min_global=("Revenu_min", "min"),
        Revenu_max_global=("Revenu_max", "max"),
        ANSTAT_min=("ANSTAT_min", "first"),
        ANSTAT_max=("ANSTAT_max", "first"),
    )
    .reset_index()
)

# Arrondir
for c in ["ecart_min_moyen", "ecart_max_moyen"]:
    synthese_grade[c] = synthese_grade[c].round(0)

print("📊 Synthèse de vérification par GRADE :")
print("=" * 120)
synthese_grade

📊 Synthèse de vérification par GRADE :
========================================================================================================================

,GRADE_PRINCIPAL,nb_mois,nb_min_anomalies,nb_max_anomalies,ecart_min_moyen,ecart_max_moyen,Revenu_min_global,Revenu_max_global,ANSTAT_min,ANSTAT_max
0,A3,24,24,24,-14998.0,36310.0,297834,799008,312833.752,761186.000
1,A4,24,24,24,-14999.0,29211.0,325286,1100803,340284.588,1051606.168
2,A5,24,0,24,0.0,37937.0,382502,1162297,379077.796,1109328.164
3,A6,24,22,24,-18900.0,23337.0,450544,1424543,473043.836,1357666.984
4,A7,24,24,8,-24057.0,53164.0,616213,1529212,646209.824,1461236.680
5,B1,24,24,24,-11945.0,14368.0,229743,354944,241688.036,338338.820
6,B3,24,24,24,-12668.0,27551.0,259793,584961,272562.592,557145.456
7,C1,24,24,24,-10321.0,13024.0,202830,288813,213498.224,275247.336
8,C2,24,24,24,-10065.0,3698.0,206856,290298,217525.340,286589.708
9,C3,24,24,24,-9713.0,17607.0,210210,380605,220210.084,362501.516
10,D1,24,24,24,-9999.0,7225.0,191417,264419,201416.876,252427.012
11,D2,24,0,0,0.0,0.0,228400,238400,208128.736,248399.896

## ✅ 9. Vérification par Barème × Grade

Même vérification, mais ventilée par **Barème (SECTEUR)** et **Grade**.
Cela permet de détecter des écarts plus fins propres à un barème spécifique.

In [14]:
# Fusionner indicateurs BAREME_G avec bornes ANSTAT
df_verif_bareme = df_indicateurs_bareme_g.merge(
    df_bornes_bareme_grade,
    left_on=["bareme", "GRADE_PRINCIPAL"],
    right_on=["SECTEUR", "GRADE"],
    how="left"
)

# Vérifications
df_verif_bareme["min_OK"] = df_verif_bareme["Revenu_min"] >= df_verif_bareme["ANSTAT_min"]
df_verif_bareme["max_OK"] = df_verif_bareme["Revenu_max"] <= df_verif_bareme["ANSTAT_max"]
df_verif_bareme["ecart_min"] = df_verif_bareme["Revenu_min"] - df_verif_bareme["ANSTAT_min"]
df_verif_bareme["ecart_max"] = df_verif_bareme["Revenu_max"] - df_verif_bareme["ANSTAT_max"]

# Résumé
nb_total = len(df_verif_bareme.dropna(subset=["ANSTAT_min"]))
nb_sans_ref = df_verif_bareme["ANSTAT_min"].isna().sum()
df_verif_clean = df_verif_bareme.dropna(subset=["ANSTAT_min"])
nb_min_ok = df_verif_clean["min_OK"].sum()
nb_max_ok = df_verif_clean["max_OK"].sum()

print("=" * 70)
print("    RÉSULTAT DE VÉRIFICATION PAR BARÈME × GRADE")
print("=" * 70)
print(f"Total lignes avec référence ANSTAT : {nb_total}")
print(f"Lignes sans référence ANSTAT       : {nb_sans_ref}")
print(f"Min OK (Revenu_min ≥ ANSTAT_min)   : {nb_min_ok}/{nb_total} ({100*nb_min_ok/nb_total:.1f}%)")
print(f"Max OK (Revenu_max ≤ ANSTAT_max)   : {nb_max_ok}/{nb_total} ({100*nb_max_ok/nb_total:.1f}%)")
print("=" * 70)

======================================================================
    RÉSULTAT DE VÉRIFICATION PAR BARÈME × GRADE
======================================================================
Total lignes avec référence ANSTAT : 1311
Lignes sans référence ANSTAT       : 0
Min OK (Revenu_min ≥ ANSTAT_min)   : 295/1311 (22.5%)
Max OK (Revenu_max ≤ ANSTAT_max)   : 277/1311 (21.1%)
======================================================================

### ⚠️ Anomalies MIN par Barème × Grade

In [15]:
anomalies_min_bareme = df_verif_clean[~df_verif_clean["min_OK"]].copy()

if len(anomalies_min_bareme) > 0:
    print(f"⚠️  {len(anomalies_min_bareme)} mois×barème×grade où Revenu_min < ANSTAT_min")
    display_cols = ["ANNEE", "MOIS", "bareme", "GRADE_PRINCIPAL", "Effectif",
                    "Revenu_min", "ANSTAT_min", "ecart_min"]
    # Afficher les 30 premières
    print(anomalies_min_bareme[display_cols].head(30).to_string(index=False))
    if len(anomalies_min_bareme) > 30:
        print(f"\n... et {len(anomalies_min_bareme) - 30} lignes supplémentaires")
else:
    print("✅ Aucune anomalie MIN par Barème × Grade")

⚠️  1016 mois×barème×grade où Revenu_min < ANSTAT_min
 ANNEE    MOIS         bareme GRADE_PRINCIPAL  Effectif  Revenu_min  ANSTAT_min  ecart_min
  2024 Janvier Barême Général              A3      8996      297834  312833.752 -14999.752
  2024 Janvier Barême Général              A4      4280      325286  340284.588 -14998.588
  2024 Janvier Barême Général              A6       433      452677  473043.836 -20366.836
  2024 Janvier Barême Général              A7       198      620090  646209.824 -26119.824
  2024 Janvier Barême Général              B1        44      231688  241688.036 -10000.036
  2024 Janvier Barême Général              B3     13942      260063  272562.592 -12499.592
  2024 Janvier Barême Général              C1      7641      203500  213498.224  -9998.224
  2024 Janvier Barême Général              C2      4638      207526  217525.340  -9999.340
  2024 Janvier Barême Général              C3      6655      210212  220210.084  -9998.084
  2024 Janvier Barême Général              D1      4327      191417  201416.876  -9999.876
  2024 Février Barême Général              A3      9292      297836  312833.752 -14997.752
  2024 Février Barême Général              A4      4377      325286  340284.588 -14998.588
  2024 Février Barême Général              A6       429      452677  473043.836 -20366.836
  2024 Février Barême Général              A7       203      620090  646209.824 -26119.824
  2024 Février Barême Général              B1        45      231688  241688.036 -10000.036
  2024 Février Barême Général              B3     14162      260064  272562.592 -12498.592
  2024 Février Barême Général              C1      7729      202830  213498.224 -10668.224
  2024 Février Barême Général              C2      4635      206856  217525.340 -10669.340
  2024 Février Barême Général              C3      6651      210212  220210.084  -9998.084
  2024 Février Barême Général              D1      4347      191417  201416.876  -9999.876
  2024    Mars Barême Général              A3      9479      297836  312833.752 -14997.752
  2024    Mars Barême Général              A4      4524      325286  340284.588 -14998.588
  2024    Mars Barême Général              A6       426      452677  473043.836 -20366.836
  2024    Mars Barême Général              A7       204      620090  646209.824 -26119.824
  2024    Mars Barême Général              B1        45      231688  241688.036 -10000.036
  2024    Mars Barême Général              B3     14478      260064  272562.592 -12498.592
  2024    Mars Barême Général              C1      7852      202944  213498.224 -10554.224
  2024    Mars Barême Général              C2      4634      207526  217525.340  -9999.340
  2024    Mars Barême Général              C3      6659      210212  220210.084  -9998.084
  2024    Mars Barême Général              D1      4427      191417  201416.876  -9999.876

... et 986 lignes supplémentaires

### ⚠️ Anomalies MAX par Barème × Grade

In [16]:
anomalies_max_bareme = df_verif_clean[~df_verif_clean["max_OK"]].copy()

if len(anomalies_max_bareme) > 0:
    print(f"⚠️  {len(anomalies_max_bareme)} mois×barème×grade où Revenu_max > ANSTAT_max")
    display_cols = ["ANNEE", "MOIS", "bareme", "GRADE_PRINCIPAL", "Effectif",
                    "Revenu_max", "ANSTAT_max", "ecart_max"]
    print(anomalies_max_bareme[display_cols].head(30).to_string(index=False))
    if len(anomalies_max_bareme) > 30:
        print(f"\n... et {len(anomalies_max_bareme) - 30} lignes supplémentaires")
else:
    print("✅ Aucune anomalie MAX par Barème × Grade")

⚠️  1034 mois×barème×grade où Revenu_max > ANSTAT_max
 ANNEE    MOIS         bareme GRADE_PRINCIPAL  Effectif  Revenu_max  ANSTAT_max  ecart_max
  2024 Janvier Barême Général              A3      8996      598304  570569.176  27734.824
  2024 Janvier Barême Général              A4      4280      692502  662453.868  30048.132
  2024 Janvier Barême Général              A5      1612      720324  687823.356  32500.644
  2024 Janvier Barême Général              A6       433      728379  695877.588  32501.412
  2024 Janvier Barême Général              A7       198      768416  750914.840  17501.160
  2024 Janvier Barême Général              B3     13942      466517  445728.580  20788.420
  2024 Janvier Barême Général              C1      7641      274325  261823.616  12501.384
  2024 Janvier Barême Général              C2      4638      290297  276589.708  13707.292
  2024 Janvier Barême Général              C3      6655      320568  306121.892  14446.108
  2024 Janvier Barême Général              D1      4327      250950  239003.292  11946.708
  2024 Février Barême Général              A3      9292      598070  570569.176  27500.824
  2024 Février Barême Général              A4      4377      695250  662453.868  32796.132
  2024 Février Barême Général              A5      1611      721434  687823.356  33610.644
  2024 Février Barême Général              A6       429      728379  695877.588  32501.412
  2024 Février Barême Général              A7       203      780954  750914.840  30039.160
  2024 Février Barême Général              B3     14162      466517  445728.580  20788.420
  2024 Février Barême Général              C1      7729      274783  261823.616  12959.384
  2024 Février Barême Général              C2      4635      290063  276589.708  13473.292
  2024 Février Barême Général              C3      6651      320568  306121.892  14446.108
  2024 Février Barême Général              D1      4347      250950  239003.292  11946.708
  2024    Mars Barême Général              A3      9479      598558  570569.176  27988.824
  2024    Mars Barême Général              A4      4524      694955  662453.868  32501.132
  2024    Mars Barême Général              A5      1614      720324  687823.356  32500.644
  2024    Mars Barême Général              A6       426      728379  695877.588  32501.412
  2024    Mars Barême Général              A7       204      768649  750914.840  17734.160
  2024    Mars Barême Général              B3     14478      467106  445728.580  21377.420
  2024    Mars Barême Général              C1      7852      274325  261823.616  12501.384
  2024    Mars Barême Général              C2      4634      290297  276589.708  13707.292
  2024    Mars Barême Général              C3      6659      320568  306121.892  14446.108
  2024    Mars Barême Général              D1      4427      250950  239003.292  11946.708

... et 1004 lignes supplémentaires

### 📊 Synthèse par Barème × Grade (vue agrégée)

In [17]:
synthese_bareme = (
    df_verif_clean
    .groupby(["bareme", "GRADE_PRINCIPAL"])
    .agg(
        nb_mois=("ANNEE", "count"),
        nb_min_anomalies=("min_OK", lambda x: (~x).sum()),
        nb_max_anomalies=("max_OK", lambda x: (~x).sum()),
        Revenu_min_global=("Revenu_min", "min"),
        Revenu_max_global=("Revenu_max", "max"),
        ANSTAT_min=("ANSTAT_min", "first"),
        ANSTAT_max=("ANSTAT_max", "first"),
    )
    .reset_index()
)

# Filtrer pour ne montrer que ceux avec anomalies
synthese_avec_anomalies = synthese_bareme[
    (synthese_bareme["nb_min_anomalies"] > 0) | (synthese_bareme["nb_max_anomalies"] > 0)
]

if len(synthese_avec_anomalies) > 0:
    print(f"⚠️  {len(synthese_avec_anomalies)} combinaisons Barème×Grade avec au moins une anomalie :")
    print(synthese_avec_anomalies.to_string(index=False))
else:
    print("✅ Aucune anomalie détectée par Barème × Grade")

print(f"\n📊 Tableau complet ({len(synthese_bareme)} combinaisons) :")
synthese_bareme

⚠️  52 combinaisons Barème×Grade avec au moins une anomalie :
              bareme GRADE_PRINCIPAL  nb_mois  nb_min_anomalies  nb_max_anomalies  Revenu_min_global  Revenu_max_global  ANSTAT_min  ANSTAT_max
      Barême Général              A3       24                24                24             297834             599010  312833.752  570569.176
      Barême Général              A4       24                24                24             325286             695250  340284.588  662453.868
      Barême Général              A5       24                 0                24             382502             722210  379077.796  687823.356
      Barême Général              A6       24                 9                24             452677             730180  473043.836  695877.588
      Barême Général              A7       24                23                24             616213             787145  646209.824  750914.840
      Barême Général              B1       24                24                16             231688             353655  241688.036  338338.820
      Barême Général              B3       24                24                24             260063             467889  272562.592  445728.580
      Barême Général              C1       24                24                24             202830             274895  213498.224  261823.616
      Barême Général              C2       24                24                24             206856             290298  217525.340  276589.708
      Barême Général              C3       24                24                24             210210             321422  220210.084  306121.892
      Barême Général              D1       24                24                24             191417             250950  201416.876  239003.292
          CORPS DIPL              A4       24                12                24             477946             646011  492945.508  617786.104
          CORPS DIPL              A5       24                16                24             664476             828836  696850.472  789474.140
          CORPS DIPL              A6       24                18                12             804082             967617  835114.788  929080.828
          CORPS DIPL              A7       24                17                17             926240            1099725  974721.476 1051236.680
          CORPS PREF              A7       24                24                 2             686975            1523585  722945.508 1461236.680
     Cadre-Sup-Santé              A4       24                24                24             407405             779436  427403.188  749572.468
     Cadre-Sup-Santé              A5       24                21                24             434905             792334  446196.396  754941.956
     Cadre-Sup-Santé              A6       24                 1                24             530163             801074  540162.436  762996.188
     Cadre-Sup-Santé              A7       24                 8                24             703330             858844  713328.424  818033.440
      ENS SEC & PRIM              A3       24                24                24             398882             799008  418881.140  761186.000
      ENS SEC & PRIM              A4       24                24                24             437072             860480  457070.952  819511.392
      ENS SEC & PRIM              A5       24                24                24             556592             911083  579091.224  867701.204
      ENS SEC & PRIM              A6       24                23                11             749108            1072736  779104.652 1022073.984
      ENS SEC & PRIM              A7       24                23                 1             891397            1120700  921396.084 1094562.072
      ENS SEC & PRIM              B3       24                24                24             342132             584961  357132.028  557145.456
      ENS SEC & PRIM              C3       24                24                24             266776             380605  279274.452  362501.516
             ENS SUP              A4       24                24                24             656667            1100803  689165.728 1051606.168
             ENS SUP              A5       24                24                24             805719            1162297  820718.184 1109328.164
             ENS SUP              A6       24                24                24            1084701            1424543 1114697.652 1357666.984
             ENS SUP              A7       24                24                12            1240417            1514138 1270412.804 1443578.792
              GREFFE              A3       24                24                24             366898             723965  381898.120  690643.680
              GREFFE              A4       24                24                24             406061             851336  426060.816  812663.952
              GREFFE              B3       24                24                24             309915             551001  324915.100  524928.528
       Informaticien              A3       24                24                23             297836             598842  312833.752  570569.176
       Informaticien              A4       24                24                 5             325286             675572  340284.588  662453.868
       Informaticien              A5       24                 0                20             384768             716368  379077.796  687823.356
       Informaticien              A6       24                14                24             450544             729488  473043.836  695877.588
       Informaticien              A7       24                24                 3             616213             780217  646209.824  750914.840
       Informaticien              B1       24                 6                 0             239743             328339  241688.036  338338.820
       Informaticien              B3       24                24                24             259793             467480  272562.592  445728.580
          MAGISTRAT               A7       24                24                 4             690287            1529212  722945.508 1461236.680
SECRETAIRE DIRECTION              B1       24                24                24             229743             354944  241688.036  338338.820
SECRETAIRE DIRECTION              B3       24                24                24             260064             467812  272562.592  445728.580
          Tech-Santé              A3       24                24                24             300385             599026  312833.752  570569.176
          Tech-Santé              A4       24                24                24             325286             695234  340284.588  662453.868
          Tech-Santé              A5       24                 0                12             518082             707591  379077.796  687823.356
          Tech-Santé              A6       24                 0                24             598859             696851  473043.836  695877.588
          Tech-Santé              B3       24                24                24             260064             467894  272562.592  445728.580
          Tech-Santé              C1       24                24                24             215668             288813  226921.944  275247.336
          Tech-Santé              C3       15                 9                 8             223634             334993  233633.804  319545.612
          Tech-Santé              D1       24                24                24             204237             264419  214840.596  252427.012

📊 Tableau complet (55 combinaisons) :

,bareme,GRADE_PRINCIPAL,nb_mois,nb_min_anomalies,nb_max_anomalies,Revenu_min_global,Revenu_max_global,ANSTAT_min,ANSTAT_max
0,Barême Général,A3,24,24,24,297834,599010,312833.752,570569.176
1,Barême Général,A4,24,24,24,325286,695250,340284.588,662453.868
2,Barême Général,A5,24,0,24,382502,722210,379077.796,687823.356
3,Barême Général,A6,24,9,24,452677,730180,473043.836,695877.588
4,Barême Général,A7,24,23,24,616213,787145,646209.824,750914.840
5,Barême Général,B1,24,24,16,231688,353655,241688.036,338338.820
6,Barême Général,B3,24,24,24,260063,467889,272562.592,445728.580
7,Barême Général,C1,24,24,24,202830,274895,213498.224,261823.616
8,Barême Général,C2,24,24,24,206856,290298,217525.340,276589.708
9,Barême Général,C3,24,24,24,210210,321422,220210.084,306121.892
10,Barême Général,D1,24,24,24,191417,250950,201416.876,239003.292
11,Barême Général,D2,24,0,0,228400,238400,208128.736,248399.896
12,CORPS DIPL,A4,24,12,24,477946,646011,492945.508,617786.104
13,CORPS DIPL,A5,24,16,24,664476,828836,696850.472,789474.140
14,CORPS DIPL,A6,24,18,12,804082,967617,835114.788,929080.828
15,CORPS DIPL,A7,24,17,17,926240,1099725,974721.476,1051236.680
16,CORPS PREF,A7,24,24,2,686975,1523585,722945.508,1461236.680
17,Cadre-Sup-Santé,A4,24,24,24,407405,779436,427403.188,749572.468
18,Cadre-Sup-Santé,A5,24,21,24,434905,792334,446196.396,754941.956
19,Cadre-Sup-Santé,A6,24,1,24,530163,801074,540162.436,762996.188
20,Cadre-Sup-Santé,A7,24,8,24,703330,858844,713328.424,818033.440
21,ENS SEC & PRIM,A3,24,24,24,398882,799008,418881.140,761186.000
22,ENS SEC & PRIM,A4,24,24,24,437072,860480,457070.952,819511.392
23,ENS SEC & PRIM,A5,24,24,24,556592,911083,579091.224,867701.204
24,ENS SEC & PRIM,A6,24,23,11,749108,1072736,779104.652,1022073.984
25,ENS SEC & PRIM,A7,24,23,1,891397,1120700,921396.084,1094562.072
26,ENS SEC & PRIM,B3,24,24,24,342132,584961,357132.028,557145.456
27,ENS SEC & PRIM,C3,24,24,24,266776,380605,279274.452,362501.516
28,ENS SUP,A4,24,24,24,656667,1100803,689165.728,1051606.168
29,ENS SUP,A5,24,24,24,805719,1162297,820718.184,1109328.164
30,ENS SUP,A6,24,24,24,1084701,1424543,1114697.652,1357666.984
31,ENS SUP,A7,24,24,12,1240417,1514138,1270412.804,1443578.792
32,GREFFE,A3,24,24,24,366898,723965,381898.120,690643.680
33,GREFFE,A4,24,24,24,406061,851336,426060.816,812663.952
34,GREFFE,B3,24,24,24,309915,551001,324915.100,524928.528
35,Informaticien,A3,24,24,23,297836,598842,312833.752,570569.176
36,Informaticien,A4,24,24,5,325286,675572,340284.588,662453.868
37,Informaticien,A5,24,0,20,384768,716368,379077.796,687823.356
38,Informaticien,A6,24,14,24,450544,729488,473043.836,695877.588
39,Informaticien,A7,24,24,3,616213,780217,646209.824,750914.840
40,Informaticien,B1,24,6,0,239743,328339,241688.036,338338.820
41,Informaticien,B3,24,24,24,259793,467480,272562.592,445728.580
42,Informaticien,C2,24,0,0,250716,266590,217525.340,276589.708
43,MAGISTRAT,A7,24,24,4,690287,1529212,722945.508,1461236.680
44,SECRETAIRE DIRECTION,A3,24,0,0,502848,557494,312833.752,570569.176
45,SECRETAIRE DIRECTION,B1,24,24,24,229743,354944,241688.036,338338.820
46,SECRETAIRE DIRECTION,B3,24,24,24,260064,467812,272562.592,445728.580
47,Tech-Santé,A3,24,24,24,300385,599026,312833.752,570569.176
48,Tech-Santé,A4,24,24,24,325286,695234,340284.588,662453.868
49,Tech-Santé,A5,24,0,12,518082,707591,379077.796,687823.356
50,Tech-Santé,A6,24,0,24,598859,696851,473043.836,695877.588
51,Tech-Santé,B3,24,24,24,260064,467894,272562.592,445728.580
52,Tech-Santé,C1,24,24,24,215668,288813,226921.944,275247.336
53,Tech-Santé,C3,15,9,8,223634,334993,233633.804,319545.612
54,Tech-Santé,D1,24,24,24,204237,264419,214840.596,252427.012

## 🔗 10. Vérification de correspondance des noms SECTEUR / bareme

On vérifie que les noms de barèmes dans les indicateurs correspondent aux noms de SECTEUR dans ANSTAT.

In [18]:
secteurs_anstat = set(df_anstat["SECTEUR"].unique())
baremes_indicateurs = set(df_indicateurs_bareme_g["bareme"].unique())

print("SECTEURS dans ANSTAT :")
for s in sorted(secteurs_anstat):
    match = "✅" if s in baremes_indicateurs else "❌"
    print(f"  {match} {s}")

print(f"\nBarèmes dans indicateurs :")
for b in sorted(baremes_indicateurs):
    match = "✅" if b in secteurs_anstat else "❌"
    print(f"  {match} {b}")

# Identifier les non-matchés
dans_anstat_pas_indicateurs = secteurs_anstat - baremes_indicateurs
dans_indicateurs_pas_anstat = baremes_indicateurs - secteurs_anstat

if dans_anstat_pas_indicateurs:
    print(f"\n⚠️  SECTEURS dans ANSTAT absents des indicateurs : {dans_anstat_pas_indicateurs}")
if dans_indicateurs_pas_anstat:
    print(f"⚠️  Barèmes dans indicateurs absents d'ANSTAT : {dans_indicateurs_pas_anstat}")
if not dans_anstat_pas_indicateurs and not dans_indicateurs_pas_anstat:
    print("\n✅ Correspondance parfaite entre ANSTAT et indicateurs")

SECTEURS dans ANSTAT :
  ✅ Barême Général
  ✅ CORPS DIPL
  ✅ CORPS PREF
  ✅ Cadre-Sup-Santé
  ✅ ENS SEC & PRIM
  ✅ ENS SUP
  ✅ GREFFE
  ✅ Informaticien
  ✅ MAGISTRAT
  ✅ SECRETAIRE DIRECTION
  ✅ Tech-Santé
  ❌ para militaire

Barèmes dans indicateurs :
  ✅ Barême Général
  ✅ CORPS DIPL
  ✅ CORPS PREF
  ✅ Cadre-Sup-Santé
  ✅ ENS SEC & PRIM
  ✅ ENS SUP
  ✅ GREFFE
  ✅ Informaticien
  ✅ MAGISTRAT
  ✅ SECRETAIRE DIRECTION
  ✅ Tech-Santé

⚠️  SECTEURS dans ANSTAT absents des indicateurs : {'para militaire'}

## 💾 11. Export des résultats de vérification

In [ ]:
# Export du résultat complet
with pd.ExcelWriter("resultats_verification_anstat_vs_indicateurs.xlsx", engine="openpyxl") as writer:
    # Synthèse par Grade
    synthese_grade.to_excel(writer, sheet_name="Synthese_par_Grade", index=False)
    
    # Synthèse par Barème × Grade
    synthese_bareme.to_excel(writer, sheet_name="Synthese_Bareme_Grade", index=False)
    
    # Anomalies MIN par Grade
    if len(anomalies_min_grade) > 0:
        cols_export = ["ANNEE", "MOIS", "GRADE_PRINCIPAL", "Effectif",
                       "Revenu_min", "ANSTAT_min", "ecart_min"]
        anomalies_min_grade[cols_export].to_excel(writer, sheet_name="Anomalies_MIN_Grade", index=False)
    
    # Anomalies MAX par Grade
    if len(anomalies_max_grade) > 0:
        cols_export = ["ANNEE", "MOIS", "GRADE_PRINCIPAL", "Effectif",
                       "Revenu_max", "ANSTAT_max", "ecart_max"]
        anomalies_max_grade[cols_export].to_excel(writer, sheet_name="Anomalies_MAX_Grade", index=False)
    
    # Anomalies MIN par Barème × Grade
    if len(anomalies_min_bareme) > 0:
        cols_export = ["ANNEE", "MOIS", "bareme", "GRADE_PRINCIPAL", "Effectif",
                       "Revenu_min", "ANSTAT_min", "ecart_min"]
        anomalies_min_bareme[cols_export].to_excel(writer, sheet_name="Anomalies_MIN_Bareme", index=False)
    
    # Anomalies MAX par Barème × Grade
    if len(anomalies_max_bareme) > 0:
        cols_export = ["ANNEE", "MOIS", "bareme", "GRADE_PRINCIPAL", "Effectif",
                       "Revenu_max", "ANSTAT_max", "ecart_max"]
        anomalies_max_bareme[cols_export].to_excel(writer, sheet_name="Anomalies_MAX_Bareme", index=False)
    
    # Bornes ANSTAT de référence
    df_bornes_grade.to_excel(writer, sheet_name="Ref_ANSTAT_Grade", index=False)
    df_bornes_bareme_grade.to_excel(writer, sheet_name="Ref_ANSTAT_Bareme_Grade", index=False)

print("✅ Résultats exportés dans 'resultats_verification_anstat_vs_indicateurs.xlsx'")
print(f"   Feuilles créées dans le fichier Excel")

## 📝 12. Conclusion

Ce notebook a permis de :

1. ✅ Créer le fichier `montant_brut_sans_indemnites.xlsx` avec la colonne calculée
2. ✅ Vérifier les **min/max par Grade** entre ANSTAT et les indicateurs
3. ✅ Vérifier les **min/max par Barème × Grade** entre ANSTAT et les indicateurs
4. ✅ Exporter les résultats détaillés pour analyse

**Interprétation des résultats** :
- Un `Revenu_min < ANSTAT_min` indique qu'il existe des agents payés **en dessous** de la grille salariale
- Un `Revenu_max > ANSTAT_max` indique qu'il existe des agents payés **au-dessus** de la grille salariale
- Ces écarts peuvent s'expliquer par des primes exceptionnelles, des erreurs de saisie, ou des régimes spéciaux